import type { AppLocale } from "./i18n";

const en = {
  nav: "App update", title: "Keep the app up to date", intro: "Check a signed update feed and install only after your approval.", autoCheck: "Check automatically when the app starts", currentVersion: "Current version", feedUrl: "Update feed URL", feedHelp: "Leave blank to use the official feed built into the app. Only credential-free HTTPS URLs are accepted.", saveFeed: "Save settings", check: "Check for updates", checking: "Checking…", notConfigured: "No update feed is configured yet.", latest: "This app is up to date.", available: "A new version is available", releaseNotes: "Release notes", publishedAt: "Published", install: "Download, verify, and update", installing: "Downloading and verifying…", verified: "Signature verified. Starting the updater…", consent: "Download and install version {version}? The app closes only after signature verification succeeds.", stopServers: "Stop every game server before updating the app.", failureSafe: "If checking, downloading, or signature verification fails, the currently installed app is kept.", settingsSaved: "Update settings saved", startupAvailable: "App version {version} is available. Open App settings > App update to review it.", browserOnly: "Update installation is available only in the installed Windows app.", endpointInvalid: "Enter a credential-free HTTPS update feed URL.", downloadProgress: "Downloaded {downloaded} of {total}", downloadProgressUnknown: "Downloaded {downloaded}", signed: "Every update must pass the signature check. It cannot be disabled.", configureLater: "You can add the release feed later without replacing the signing key.", feedMode: "Update channel", customFeedActive: "A custom signed update feed is active.", advancedOptions: "Developer options", advancedHelp: "For update feed testing and alternate distribution endpoints. Most users should keep the official feed.", useOfficialFeed: "Use official feed",
} as const;

type Key = keyof typeof en;
type Catalog = Record<Key, string>;
type DeveloperOptionKey = "feedMode" | "customFeedActive" | "advancedOptions" | "advancedHelp" | "useOfficialFeed";
type BaseCatalog = Omit<Catalog, DeveloperOptionKey>;
type UnmergedCatalog = BaseCatalog & Partial<Pick<Catalog, DeveloperOptionKey>>;

const developerOptions: Record<Exclude<AppLocale, "en" | "ja">, Pick<Catalog, DeveloperOptionKey>> = {
  "zh-CN": { feedMode: "更新通道", customFeedActive: "正在使用自定义的已签名更新源。", advancedOptions: "开发者选项", advancedHelp: "此选项用于测试更新源或使用其他分发地址。大多数用户应继续使用官方更新源。", useOfficialFeed: "使用官方更新源" },
  "zh-TW": { feedMode: "更新管道", customFeedActive: "目前使用自訂的已簽署更新來源。", advancedOptions: "開發者選項", advancedHelp: "此選項用於測試更新來源或使用其他發佈位址。大多數使用者應繼續使用官方更新來源。", useOfficialFeed: "使用官方更新來源" },
  ko: { feedMode: "업데이트 채널", customFeedActive: "사용자 지정 서명 업데이트 피드를 사용 중입니다.", advancedOptions: "개발자 옵션", advancedHelp: "업데이트 피드 테스트 또는 대체 배포 주소를 위한 옵션입니다. 대부분의 사용자는 공식 피드를 그대로 사용하세요.", useOfficialFeed: "공식 피드 사용" },
  es: { feedMode: "Canal de actualización", customFeedActive: "Hay un canal de actualización firmado personalizado activo.", advancedOptions: "Opciones para desarrolladores", advancedHelp: "Para probar canales de actualización o usar destinos de distribución alternativos. La mayoría de las personas deben mantener el canal oficial.", useOfficialFeed: "Usar canal oficial" },
  de: { feedMode: "Update-Kanal", customFeedActive: "Ein benutzerdefinierter signierter Update-Feed ist aktiv.", advancedOptions: "Entwickleroptionen", advancedHelp: "Für Tests von Update-Feeds und alternative Verteilungsziele. Die meisten Nutzer sollten den offiziellen Feed beibehalten.", useOfficialFeed: "Offiziellen Feed verwenden" },
  fr: { feedMode: "Canal de mise à jour", customFeedActive: "Un flux de mise à jour signé personnalisé est actif.", advancedOptions: "Options pour les développeurs", advancedHelp: "Pour tester les flux de mise à jour ou utiliser d’autres destinations de distribution. La plupart des utilisateurs doivent conserver le flux officiel.", useOfficialFeed: "Utiliser le flux officiel" },
  "pt-BR": { feedMode: "Canal de atualização", customFeedActive: "Um feed de atualização assinado personalizado está ativo.", advancedOptions: "Opções do desenvolvedor", advancedHelp: "Para testar feeds de atualização ou usar destinos alternativos de distribuição. A maioria das pessoas deve manter o feed oficial.", useOfficialFeed: "Usar feed oficial" },
};

const baseCatalogs: Record<AppLocale, UnmergedCatalog> = {
  en,
  ja: { nav: "アプリの更新", title: "アプリを最新の状態に保つ", intro: "署名付きの更新フィードを確認し、ユーザーが許可した場合だけインストールします。", autoCheck: "アプリ起動時に自動確認する", currentVersion: "現在のバージョン", feedUrl: "更新フィードURL", feedHelp: "空欄の場合はアプリ内蔵の公式フィードを使用します。認証情報を含まないHTTPS URLだけ使用できます。", saveFeed: "設定を保存", check: "更新を確認", checking: "確認しています…", notConfigured: "更新フィードがまだ設定されていません。", latest: "このアプリは最新です。", available: "新しいバージョンがあります", releaseNotes: "更新内容", publishedAt: "公開日時", install: "ダウンロード・検証して更新", installing: "ダウンロードと署名検証中…", verified: "署名を確認しました。更新を開始します…", consent: "バージョン{version}をダウンロードしてインストールしますか？署名検証に成功した後だけアプリを閉じます。", stopServers: "アプリ更新前にすべてのゲームサーバーを停止してください。", failureSafe: "確認、ダウンロード、署名検証のいずれかに失敗した場合、現在のアプリをそのまま残します。", settingsSaved: "更新設定を保存しました", startupAvailable: "アプリのバージョン{version}があります。設定の「アプリの更新」で内容を確認してください。", browserOnly: "更新のインストールはWindowsへインストールしたアプリでのみ利用できます。", endpointInvalid: "認証情報を含まないHTTPSの更新フィードURLを入力してください。", downloadProgress: "{total}中{downloaded}を取得", downloadProgressUnknown: "{downloaded}を取得", signed: "すべての更新で署名検証が必須です。無効にはできません。", configureLater: "署名鍵を変更せず、リリースフィードだけ後から設定できます。", feedMode: "更新チャンネル", customFeedActive: "カスタムの署名付き更新フィードを使用中です。", advancedOptions: "開発者向け詳細設定", advancedHelp: "更新フィードのテストや代替配布先を使う開発者向けです。通常は公式フィードのまま使用してください。", useOfficialFeed: "公式フィードを使用" },
  "zh-CN": { nav: "应用更新", title: "让应用保持最新", intro: "检查已签名的更新源，并且仅在您允许后安装。", autoCheck: "应用启动时自动检查", currentVersion: "当前版本", feedUrl: "更新源 URL", feedHelp: "留空则使用应用内置的官方更新源。只接受不含凭据的 HTTPS URL。", saveFeed: "保存设置", check: "检查更新", checking: "正在检查…", notConfigured: "尚未配置更新源。", latest: "应用已是最新版本。", available: "有新版本可用", releaseNotes: "更新说明", publishedAt: "发布时间", install: "下载、验证并更新", installing: "正在下载并验证签名…", verified: "签名已验证，正在启动更新程序…", consent: "下载并安装版本 {version}？只有签名验证成功后应用才会关闭。", stopServers: "更新应用前请停止所有游戏服务器。", failureSafe: "如果检查、下载或签名验证失败，将保留当前安装的应用。", settingsSaved: "已保存更新设置", startupAvailable: "应用版本 {version} 可用。请在应用设置 > 应用更新中查看。", browserOnly: "更新安装仅适用于已安装的 Windows 应用。", endpointInvalid: "请输入不含凭据的 HTTPS 更新源 URL。", downloadProgress: "已下载 {downloaded} / {total}", downloadProgressUnknown: "已下载 {downloaded}", signed: "每次更新都必须通过签名验证，无法禁用。", configureLater: "之后可以添加发布源，无需更换签名密钥。" },
  "zh-TW": { nav: "應用程式更新", title: "讓應用程式保持最新", intro: "檢查已簽署的更新來源，並只在您允許後安裝。", autoCheck: "應用程式啟動時自動檢查", currentVersion: "目前版本", feedUrl: "更新來源 URL", feedHelp: "留空時使用應用程式內建的官方來源。只接受不含認證資訊的 HTTPS URL。", saveFeed: "儲存設定", check: "檢查更新", checking: "正在檢查…", notConfigured: "尚未設定更新來源。", latest: "應用程式已是最新版本。", available: "有新版本可用", releaseNotes: "更新說明", publishedAt: "發布時間", install: "下載、驗證並更新", installing: "正在下載並驗證簽章…", verified: "簽章已驗證，正在啟動更新程式…", consent: "下載並安裝版本 {version}？只有簽章驗證成功後應用程式才會關閉。", stopServers: "更新應用程式前請停止所有遊戲伺服器。", failureSafe: "若檢查、下載或簽章驗證失敗，會保留目前安裝的應用程式。", settingsSaved: "已儲存更新設定", startupAvailable: "應用程式版本 {version} 可用。請在應用程式設定 > 應用程式更新中查看。", browserOnly: "更新安裝僅適用於已安裝的 Windows 應用程式。", endpointInvalid: "請輸入不含認證資訊的 HTTPS 更新來源 URL。", downloadProgress: "已下載 {downloaded} / {total}", downloadProgressUnknown: "已下載 {downloaded}", signed: "每次更新都必須通過簽章驗證，無法停用。", configureLater: "之後可新增發布來源，不必更換簽章金鑰。" },
  ko: { nav: "앱 업데이트", title: "앱을 최신 상태로 유지", intro: "서명된 업데이트 피드를 확인하고 사용자가 허용한 경우에만 설치합니다.", autoCheck: "앱 시작 시 자동 확인", currentVersion: "현재 버전", feedUrl: "업데이트 피드 URL", feedHelp: "비워 두면 앱에 내장된 공식 피드를 사용합니다. 인증 정보가 없는 HTTPS URL만 허용됩니다.", saveFeed: "설정 저장", check: "업데이트 확인", checking: "확인 중…", notConfigured: "업데이트 피드가 아직 설정되지 않았습니다.", latest: "이 앱은 최신 버전입니다.", available: "새 버전을 사용할 수 있습니다", releaseNotes: "릴리스 정보", publishedAt: "게시일", install: "다운로드, 검증 및 업데이트", installing: "다운로드 및 서명 검증 중…", verified: "서명을 확인했습니다. 업데이트를 시작합니다…", consent: "버전 {version}을 다운로드하고 설치할까요? 서명 검증이 성공한 후에만 앱이 닫힙니다.", stopServers: "앱을 업데이트하기 전에 모든 게임 서버를 중지하세요.", failureSafe: "확인, 다운로드 또는 서명 검증에 실패하면 현재 설치된 앱을 유지합니다.", settingsSaved: "업데이트 설정을 저장했습니다", startupAvailable: "앱 버전 {version}을 사용할 수 있습니다. 앱 설정 > 앱 업데이트에서 확인하세요.", browserOnly: "업데이트 설치는 Windows에 설치된 앱에서만 사용할 수 있습니다.", endpointInvalid: "인증 정보가 없는 HTTPS 업데이트 피드 URL을 입력하세요.", downloadProgress: "{total} 중 {downloaded} 다운로드", downloadProgressUnknown: "{downloaded} 다운로드", signed: "모든 업데이트는 서명 검증을 통과해야 하며 비활성화할 수 없습니다.", configureLater: "서명 키를 바꾸지 않고 릴리스 피드만 나중에 추가할 수 있습니다." },
  es: { nav: "Actualizar aplicación", title: "Mantén la aplicación actualizada", intro: "Comprueba un canal firmado e instala solo después de tu aprobación.", autoCheck: "Buscar al iniciar la aplicación", currentVersion: "Versión actual", feedUrl: "URL del canal de actualización", feedHelp: "Déjalo vacío para usar el canal oficial integrado. Solo se aceptan URL HTTPS sin credenciales.", saveFeed: "Guardar ajustes", check: "Buscar actualizaciones", checking: "Comprobando…", notConfigured: "Aún no hay un canal de actualización configurado.", latest: "La aplicación está actualizada.", available: "Hay una nueva versión", releaseNotes: "Notas de la versión", publishedAt: "Publicada", install: "Descargar, verificar y actualizar", installing: "Descargando y verificando firma…", verified: "Firma verificada. Iniciando actualización…", consent: "¿Descargar e instalar la versión {version}? La aplicación solo se cerrará después de verificar la firma.", stopServers: "Detén todos los servidores de juego antes de actualizar.", failureSafe: "Si falla la comprobación, descarga o firma, se conserva la aplicación instalada.", settingsSaved: "Ajustes de actualización guardados", startupAvailable: "La versión {version} está disponible. Revísala en Ajustes > Actualizar aplicación.", browserOnly: "La instalación solo está disponible en la aplicación instalada de Windows.", endpointInvalid: "Introduce una URL HTTPS sin credenciales.", downloadProgress: "Descargados {downloaded} de {total}", downloadProgressUnknown: "Descargados {downloaded}", signed: "Todas las actualizaciones deben superar la firma; no se puede desactivar.", configureLater: "Puedes añadir el canal más tarde sin sustituir la clave de firma." },
  de: { nav: "App-Update", title: "App aktuell halten", intro: "Prüft einen signierten Update-Feed und installiert nur nach Ihrer Zustimmung.", autoCheck: "Beim App-Start automatisch prüfen", currentVersion: "Aktuelle Version", feedUrl: "Update-Feed-URL", feedHelp: "Leer lassen, um den eingebauten offiziellen Feed zu verwenden. Nur HTTPS-URLs ohne Zugangsdaten sind erlaubt.", saveFeed: "Einstellungen speichern", check: "Nach Updates suchen", checking: "Prüfung läuft…", notConfigured: "Noch kein Update-Feed konfiguriert.", latest: "Die App ist aktuell.", available: "Eine neue Version ist verfügbar", releaseNotes: "Versionshinweise", publishedAt: "Veröffentlicht", install: "Herunterladen, prüfen und aktualisieren", installing: "Download und Signaturprüfung…", verified: "Signatur geprüft. Update wird gestartet…", consent: "Version {version} herunterladen und installieren? Die App wird erst nach erfolgreicher Signaturprüfung geschlossen.", stopServers: "Stoppen Sie alle Spielserver vor dem App-Update.", failureSafe: "Bei einem Fehler bei Prüfung, Download oder Signatur bleibt die installierte App erhalten.", settingsSaved: "Update-Einstellungen gespeichert", startupAvailable: "App-Version {version} ist verfügbar. Öffnen Sie App-Einstellungen > App-Update.", browserOnly: "Die Installation ist nur in der installierten Windows-App verfügbar.", endpointInvalid: "Geben Sie eine HTTPS-Feed-URL ohne Zugangsdaten ein.", downloadProgress: "{downloaded} von {total} heruntergeladen", downloadProgressUnknown: "{downloaded} heruntergeladen", signed: "Jedes Update muss die Signaturprüfung bestehen; sie kann nicht deaktiviert werden.", configureLater: "Der Release-Feed kann später ergänzt werden, ohne den Signaturschlüssel zu ändern." },
  fr: { nav: "Mise à jour", title: "Garder l’application à jour", intro: "Vérifie un flux signé et installe uniquement après votre accord.", autoCheck: "Vérifier au démarrage de l’application", currentVersion: "Version actuelle", feedUrl: "URL du flux de mise à jour", feedHelp: "Laissez vide pour utiliser le flux officiel intégré. Seules les URL HTTPS sans identifiants sont acceptées.", saveFeed: "Enregistrer", check: "Rechercher des mises à jour", checking: "Vérification…", notConfigured: "Aucun flux de mise à jour n’est encore configuré.", latest: "L’application est à jour.", available: "Une nouvelle version est disponible", releaseNotes: "Notes de version", publishedAt: "Publication", install: "Télécharger, vérifier et mettre à jour", installing: "Téléchargement et vérification…", verified: "Signature vérifiée. Démarrage de la mise à jour…", consent: "Télécharger et installer la version {version} ? L’application se ferme uniquement après vérification de la signature.", stopServers: "Arrêtez tous les serveurs de jeu avant la mise à jour.", failureSafe: "En cas d’échec de vérification, téléchargement ou signature, l’application installée est conservée.", settingsSaved: "Paramètres de mise à jour enregistrés", startupAvailable: "La version {version} est disponible. Consultez Paramètres > Mise à jour.", browserOnly: "L’installation est disponible uniquement dans l’application Windows installée.", endpointInvalid: "Saisissez une URL HTTPS sans identifiants.", downloadProgress: "{downloaded} téléchargés sur {total}", downloadProgressUnknown: "{downloaded} téléchargés", signed: "Chaque mise à jour doit réussir la vérification de signature, impossible à désactiver.", configureLater: "Vous pourrez ajouter le flux plus tard sans remplacer la clé de signature." },
  "pt-BR": { nav: "Atualização do app", title: "Mantenha o aplicativo atualizado", intro: "Verifica um feed assinado e instala somente após sua aprovação.", autoCheck: "Verificar ao iniciar o aplicativo", currentVersion: "Versão atual", feedUrl: "URL do feed de atualização", feedHelp: "Deixe em branco para usar o feed oficial integrado. Somente URLs HTTPS sem credenciais são aceitas.", saveFeed: "Salvar configurações", check: "Verificar atualizações", checking: "Verificando…", notConfigured: "Nenhum feed de atualização foi configurado.", latest: "O aplicativo está atualizado.", available: "Uma nova versão está disponível", releaseNotes: "Notas da versão", publishedAt: "Publicada em", install: "Baixar, verificar e atualizar", installing: "Baixando e verificando assinatura…", verified: "Assinatura verificada. Iniciando atualização…", consent: "Baixar e instalar a versão {version}? O aplicativo só fecha após a assinatura ser verificada.", stopServers: "Pare todos os servidores de jogo antes de atualizar.", failureSafe: "Se a verificação, download ou assinatura falhar, o aplicativo instalado será mantido.", settingsSaved: "Configurações de atualização salvas", startupAvailable: "A versão {version} está disponível. Veja em Configurações > Atualização do app.", browserOnly: "A instalação só está disponível no aplicativo Windows instalado.", endpointInvalid: "Insira uma URL HTTPS sem credenciais.", downloadProgress: "{downloaded} de {total} baixados", downloadProgressUnknown: "{downloaded} baixados", signed: "Toda atualização deve passar pela assinatura; isso não pode ser desativado.", configureLater: "Você pode adicionar o feed depois sem trocar a chave de assinatura." },
};

const catalogs: Record<AppLocale, Catalog> = Object.fromEntries(
  Object.entries(baseCatalogs).map(([locale, catalog]) => [
    locale,
    locale === "en" ? en : locale === "ja" ? catalog as Catalog : { ...catalog, ...developerOptions[locale as Exclude<AppLocale, "en" | "ja">] },
  ]),
) as Record<AppLocale, Catalog>;

const officialFeedText: Record<AppLocale, string> = {
  ja: "署名済みの公式更新フィードを使用中です。このまま使う場合は空欄のままにしてください。",
  en: "The signed official update feed is active. Leave this field blank to keep using it.",
  de: "Der signierte offizielle Update-Feed ist aktiv. Lassen Sie dieses Feld leer, um ihn weiter zu verwenden.",
  es: "El canal oficial firmado está activo. Deja este campo vacío para seguir usándolo.",
  fr: "Le flux officiel signé est actif. Laissez ce champ vide pour continuer à l’utiliser.",
  ko: "서명된 공식 업데이트 피드를 사용 중입니다. 계속 사용하려면 이 필드를 비워 두세요.",
  "pt-BR": "O feed oficial assinado está ativo. Deixe este campo em branco para continuar usando-o.",
  "zh-CN": "正在使用已签名的官方更新源。保持此字段为空即可继续使用。",
  "zh-TW": "目前使用已簽署的官方更新來源。保持此欄空白即可繼續使用。",
};

export type AppUpdateLocaleKey = Key;

export function appUpdateText(locale: AppLocale, key: Key, values: Record<string, string | number> = {}) {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), catalogs[locale][key]);
}

export function getAppUpdateCatalog(locale: AppLocale) {
  return catalogs[locale];
}

export function appUpdateOfficialFeedText(locale: AppLocale) {
  return officialFeedText[locale];
}
