import type { AppLocale } from "./i18n";

const keys = ["title", "intro", "start", "working", "friend", "host", "copy", "stop", "close", "relay", "consent", "setup", "setupHelp", "verify", "stopped", "timeout", "stopHelp", "privacy"] as const;
type Key = typeof keys[number];
const rows: Record<AppLocale, readonly string[]> = {
  ja: ["Palworldの友達を招待", "サーバーを起動してルーターの自動接続を試します。接続できない回線では中継を案内します。", "友達と遊べるようにする", "接続を準備しています…", "別の家の友達に渡すアドレス", "このPC本人のアドレス", "アドレスをコピー", "招待を停止", "閉じる", "中継で接続する", "playit.ggの規約・プライバシーを確認し、必要な公式エージェントのインストールに同意します。", "初回設定を開く", "公式画面でアカウントを連携し、Palworld用UDPトンネルの転送先を {target} にしてください。設定後は自動で接続先を取得します。", "接続先を取得しました。友達のPalworldから参加して確認してください。参加パスワードを設定した場合は別途伝えてください。", "公開していません", "サーバーの準備に時間がかかっています。コンソールを確認し、準備完了後に再試行してください。", "中継が共有されている場合は公式画面でこのトンネルを無効にしてください。サーバー停止でもゲームへの接続を終了できます。", "自動接続では自宅の公開IPを友達に伝えます。中継ではゲーム通信がplayit.ggを経由します。Windowsの通信許可が表示された場合はゲーム用UDPだけを許可してください。管理用RESTポートは公開しません。"],
  en: ["Invite Palworld friends", "Start the server and try automatic router setup. Relay setup is available if your network does not support it.", "Prepare for friends", "Preparing connection…", "Address for friends elsewhere", "Address for this PC", "Copy address", "Stop invite", "Close", "Connect using relay", "I reviewed playit.gg terms and privacy and agree to install the official agent if needed.", "Open first-time setup", "Link your account on the official page and forward a Palworld UDP tunnel to {target}. The address will appear automatically after setup.", "Address obtained. Verify by joining from your friend's Palworld. Share the join password separately if configured.", "Not published", "The server is taking longer to prepare. Check the console and retry when ready.", "For a shared relay, disable this tunnel on the official page. Stopping the game server also ends game access.", "Router setup shares your public IP with friends. Relay traffic passes through playit.gg. If Windows asks, allow only game UDP traffic; never publish the REST management port."],
  de: ["Palworld-Freunde einladen", "Server starten und automatische Router-Einrichtung versuchen. Falls nötig ist eine Weiterleitung verfügbar.", "Für Freunde vorbereiten", "Verbindung wird vorbereitet…", "Adresse für Freunde außerhalb", "Adresse für diesen PC", "Adresse kopieren", "Einladung beenden", "Schließen", "Weiterleitung verwenden", "Ich habe die Bedingungen und den Datenschutz von playit.gg gelesen und stimme der Installation des offiziellen Agenten zu, falls nötig.", "Ersteinrichtung öffnen", "Konto auf der offiziellen Seite verknüpfen und einen Palworld-UDP-Tunnel an {target} weiterleiten. Die Adresse erscheint anschließend automatisch.", "Adresse erhalten. Verbindung vom Palworld des Freundes prüfen. Ein gesetztes Beitrittspasswort separat teilen.", "Nicht veröffentlicht", "Der Server benötigt mehr Zeit. Konsole prüfen und später erneut versuchen.", "Bei gemeinsamem Dienst diesen Tunnel auf der offiziellen Seite deaktivieren. Serverstopp beendet auch den Spielzugriff.", "Die Router-Einrichtung teilt Ihre öffentliche IP. Weiterleitungsverkehr läuft über playit.gg. Unter Windows nur Spiel-UDP erlauben; den REST-Verwaltungsport nicht veröffentlichen."],
  es: ["Invitar amigos de Palworld", "Inicia el servidor e intenta configurar el router automáticamente. Si no es compatible, puedes usar un relé.", "Preparar para amigos", "Preparando conexión…", "Dirección para amigos de otra casa", "Dirección para este PC", "Copiar dirección", "Detener invitación", "Cerrar", "Conectar mediante relé", "He revisado los términos y privacidad de playit.gg y acepto instalar el agente oficial si hace falta.", "Abrir configuración inicial", "Vincula tu cuenta en la página oficial y dirige un túnel UDP de Palworld a {target}. La dirección aparecerá automáticamente.", "Dirección obtenida. Comprueba la conexión desde el Palworld de tu amigo. Comparte aparte la contraseña de acceso si existe.", "Sin publicar", "El servidor tarda en prepararse. Revisa la consola y vuelve a intentarlo.", "Si el relé es compartido, desactiva este túnel en la página oficial. Detener el servidor también corta el acceso al juego.", "La configuración del router comparte tu IP pública. El relé envía tráfico por playit.gg. En Windows permite solo UDP del juego; no publiques el puerto REST."],
  fr: ["Inviter des amis sur Palworld", "Démarre le serveur et tente la configuration automatique du routeur. Un relais est proposé si nécessaire.", "Préparer pour les amis", "Préparation de la connexion…", "Adresse pour les amis ailleurs", "Adresse pour ce PC", "Copier l’adresse", "Arrêter l’invitation", "Fermer", "Utiliser le relais", "J’ai lu les conditions et la confidentialité de playit.gg et j’accepte l’installation de l’agent officiel si nécessaire.", "Ouvrir la configuration initiale", "Associez votre compte sur le site officiel et redirigez un tunnel UDP Palworld vers {target}. L’adresse apparaîtra automatiquement.", "Adresse obtenue. Vérifiez en rejoignant depuis le Palworld d’un ami. Transmettez séparément le mot de passe si défini.", "Non publié", "Le serveur prend du temps. Consultez la console puis réessayez.", "Pour un relais partagé, désactivez ce tunnel sur le site officiel. Arrêter le serveur coupe aussi l’accès au jeu.", "La configuration du routeur partage votre IP publique. Le relais passe par playit.gg. Autorisez uniquement le trafic UDP du jeu dans Windows, jamais le port REST."],
  ko: ["Palworld 친구 초대", "서버를 시작하고 공유기 자동 설정을 시도합니다. 지원하지 않는 네트워크에서는 중계를 안내합니다.", "친구와 플레이 준비", "연결 준비 중…", "다른 집 친구에게 보낼 주소", "이 PC의 주소", "주소 복사", "초대 중지", "닫기", "중계로 연결", "playit.gg 약관과 개인정보 정책을 확인했으며 필요한 경우 공식 에이전트 설치에 동의합니다.", "최초 설정 열기", "공식 페이지에서 계정을 연결하고 Palworld UDP 터널을 {target}으로 전달하세요. 설정 후 주소가 자동으로 표시됩니다.", "주소를 받았습니다. 친구의 Palworld에서 접속해 확인하세요. 참가 비밀번호가 있으면 따로 전달하세요.", "공개 안 됨", "서버 준비가 지연됩니다. 콘솔을 확인하고 준비 후 다시 시도하세요.", "공유 중계 서비스라면 공식 페이지에서 이 터널을 비활성화하세요. 서버를 중지해도 게임 접속이 종료됩니다.", "공유기 설정은 공인 IP를 친구에게 제공합니다. 중계는 playit.gg를 거칩니다. Windows에서는 게임 UDP만 허용하고 REST 관리 포트를 공개하지 마세요."],
  "pt-BR": ["Convidar amigos ao Palworld", "Inicia o servidor e tenta configurar o roteador automaticamente. Se necessário, oferece retransmissão.", "Preparar para amigos", "Preparando conexão…", "Endereço para amigos de outra casa", "Endereço deste PC", "Copiar endereço", "Parar convite", "Fechar", "Conectar por retransmissão", "Li os termos e a privacidade do playit.gg e aceito instalar o agente oficial se necessário.", "Abrir configuração inicial", "Vincule sua conta no site oficial e encaminhe um túnel UDP Palworld para {target}. O endereço aparecerá automaticamente.", "Endereço obtido. Verifique entrando pelo Palworld do amigo. Compartilhe separadamente a senha de entrada, se definida.", "Não publicado", "O servidor demora para ficar pronto. Verifique o console e tente novamente.", "Se o serviço for compartilhado, desative este túnel no site oficial. Parar o servidor também encerra o acesso ao jogo.", "A configuração do roteador compartilha seu IP público. A retransmissão passa pelo playit.gg. No Windows, permita apenas UDP do jogo; nunca publique a porta REST."],
  "zh-CN": ["邀请 Palworld 好友", "启动服务器并尝试自动设置路由器。不支持时将提供中继设置。", "准备与好友游玩", "正在准备连接…", "发送给异地好友的地址", "本机使用的地址", "复制地址", "停止邀请", "关闭", "使用中继连接", "我已阅读 playit.gg 条款及隐私政策，并同意在需要时安装官方代理。", "打开首次设置", "在官方页面关联账号，将 Palworld UDP 隧道转发到 {target}。设置后自动显示连接地址。", "已获取地址。请让好友从 Palworld 加入验证。如设置了加入密码，请另行告知。", "未公开", "服务器准备时间较长。请检查控制台，准备完成后重试。", "共享中继服务时，请在官方页面禁用此隧道。停止服务器也会结束游戏访问。", "路由器设置会向好友提供公网 IP。中继流量经过 playit.gg。Windows 提示时仅允许游戏 UDP，切勿公开 REST 管理端口。"],
  "zh-TW": ["邀請 Palworld 好友", "啟動伺服器並嘗試自動設定路由器。不支援時將提供中繼設定。", "準備與好友遊玩", "正在準備連線…", "傳給異地好友的位址", "本機使用的位址", "複製位址", "停止邀請", "關閉", "使用中繼連線", "我已閱讀 playit.gg 條款及隱私政策，並同意在需要時安裝官方代理程式。", "開啟首次設定", "在官方頁面連結帳號，將 Palworld UDP 通道轉送到 {target}。設定後自動顯示連線位址。", "已取得位址。請讓好友從 Palworld 加入驗證。如設定加入密碼，請另行告知。", "未公開", "伺服器準備時間較長。請檢查主控台，準備完成後重試。", "共用中繼服務時，請在官方頁面停用此通道。停止伺服器也會結束遊戲存取。", "路由器設定會向好友提供公用 IP。中繼流量經過 playit.gg。Windows 提示時僅允許遊戲 UDP，切勿公開 REST 管理連接埠。"],
};
export const getPalworldInviteCatalog = (locale: AppLocale) => Object.fromEntries(keys.map((key, index) => [key, rows[locale][index]])) as Record<Key, string>;
export const palworldInviteText = (locale: AppLocale, key: Key, target = "") => getPalworldInviteCatalog(locale)[key].replaceAll("{target}", target);
