import type { AppLocale } from "./i18n";

const ja = {
  serverFiles: "サーバーファイル", openWindows: "Windowsで開く", newFile: "新規ファイル", newFolder: "新規フォルダー", upload: "アップロード",
  sandboxNote: "アクセス範囲はこのサーバーフォルダー内だけです。ファイル変更はサーバー停止中のみ実行できます。", parentFolder: "上のフォルダー", emptyFolder: "このフォルダーは空です。",
  download: "ダウンロード", rename: "名前変更", delete: "削除", unsaved: "未保存", saved: "保存済み", save: "保存",
  unsupportedEdit: "この形式はアプリ内編集に対応していません。ダウンロードまたはWindowsで開いて確認してください。", selectFile: "ファイルを選択すると内容と操作を表示します。",
  discardChanges: "保存していない変更を破棄して別の項目を開きますか？", newFilePrompt: "新しいファイル名", newFolderPrompt: "新しいフォルダー名", renamePrompt: "新しい名前",
  deleteConfirm: "「{name}」を完全に削除しますか？\nこの操作は元に戻せません。", uploadTitle: "サーバーへ追加するファイルを選択", downloadTitle: "ファイルを保存",
  accessLog: "アクセスログ", searchAudit: "操作・詳細を検索", noAudit: "記録された操作はありません。",
  backups: "バックアップ", backupLocation: "保存先", createNow: "今すぐ作成", creating: "作成中…", backupStopNote: "整合性を守るため、安全停止してからバックアップします。",
  validBackup: "整合性OK", invalidBackup: "要確認", restore: "復元", deleteBackup: "バックアップを削除", noBackups: "バックアップはまだありません。",
  backupCreated: "Palworldバックアップを作成しました", backupRestored: "Palworldバックアップを復元しました", backupDeleted: "バックアップを削除しました",
  restoreConfirm: "「{name}」を復元しますか？\n現在の状態は復元直前バックアップとして保存されます。", deleteBackupConfirm: "「{name}」を削除しますか？",
};

type Key = keyof typeof ja;
type Copy = Record<Key, string>;

const copies: Record<AppLocale, Copy> = {
  ja,
  en: { serverFiles:"Server files",openWindows:"Open in Windows",newFile:"New file",newFolder:"New folder",upload:"Upload",sandboxNote:"Access is limited to this server folder. Files can be changed only while the server is stopped.",parentFolder:"Parent folder",emptyFolder:"This folder is empty.",download:"Download",rename:"Rename",delete:"Delete",unsaved:"Unsaved",saved:"Saved",save:"Save",unsupportedEdit:"This format cannot be edited in the app. Download it or open it in Windows to inspect it.",selectFile:"Select a file to view its contents and actions.",discardChanges:"Discard unsaved changes and open another item?",newFilePrompt:"New file name",newFolderPrompt:"New folder name",renamePrompt:"New name",deleteConfirm:"Permanently delete “{name}”?\nThis cannot be undone.",uploadTitle:"Select a file to add to the server",downloadTitle:"Save file",accessLog:"Access log",searchAudit:"Search actions and details",noAudit:"No actions have been recorded.",backups:"Backups",backupLocation:"Location",createNow:"Create now",creating:"Creating…",backupStopNote:"Stop the server safely before backing up to preserve consistency.",validBackup:"Integrity OK",invalidBackup:"Needs review",restore:"Restore",deleteBackup:"Delete backup",noBackups:"No backups yet.",backupCreated:"Palworld backup created",backupRestored:"Palworld backup restored",backupDeleted:"Backup deleted",restoreConfirm:"Restore “{name}”?\nThe current state will be saved as a pre-restore backup.",deleteBackupConfirm:"Delete “{name}”?" },
  "zh-CN": { serverFiles:"服务器文件",openWindows:"在 Windows 中打开",newFile:"新建文件",newFolder:"新建文件夹",upload:"上传",sandboxNote:"访问范围仅限此服务器文件夹。只有服务器停止时才能修改文件。",parentFolder:"上级文件夹",emptyFolder:"此文件夹为空。",download:"下载",rename:"重命名",delete:"删除",unsaved:"未保存",saved:"已保存",save:"保存",unsupportedEdit:"应用内无法编辑此格式。请下载或在 Windows 中打开查看。",selectFile:"选择文件后可查看内容和操作。",discardChanges:"放弃未保存的更改并打开其他项目吗？",newFilePrompt:"新文件名",newFolderPrompt:"新文件夹名",renamePrompt:"新名称",deleteConfirm:"永久删除“{name}”吗？\n此操作无法撤销。",uploadTitle:"选择要添加到服务器的文件",downloadTitle:"保存文件",accessLog:"访问日志",searchAudit:"搜索操作和详情",noAudit:"尚无操作记录。",backups:"备份",backupLocation:"保存位置",createNow:"立即创建",creating:"正在创建…",backupStopNote:"为保持一致性，请安全停止服务器后再备份。",validBackup:"完整性正常",invalidBackup:"需要检查",restore:"恢复",deleteBackup:"删除备份",noBackups:"尚无备份。",backupCreated:"已创建 Palworld 备份",backupRestored:"已恢复 Palworld 备份",backupDeleted:"已删除备份",restoreConfirm:"恢复“{name}”吗？\n当前状态将保存为恢复前备份。",deleteBackupConfirm:"删除“{name}”吗？" },
  "zh-TW": { serverFiles:"伺服器檔案",openWindows:"在 Windows 中開啟",newFile:"新增檔案",newFolder:"新增資料夾",upload:"上傳",sandboxNote:"存取範圍僅限此伺服器資料夾。只有伺服器停止時才能修改檔案。",parentFolder:"上層資料夾",emptyFolder:"此資料夾是空的。",download:"下載",rename:"重新命名",delete:"刪除",unsaved:"未儲存",saved:"已儲存",save:"儲存",unsupportedEdit:"應用程式內無法編輯此格式。請下載或在 Windows 中開啟查看。",selectFile:"選取檔案後可查看內容與操作。",discardChanges:"放棄未儲存的變更並開啟其他項目嗎？",newFilePrompt:"新檔案名稱",newFolderPrompt:"新資料夾名稱",renamePrompt:"新名稱",deleteConfirm:"永久刪除「{name}」嗎？\n此操作無法復原。",uploadTitle:"選取要加入伺服器的檔案",downloadTitle:"儲存檔案",accessLog:"存取記錄",searchAudit:"搜尋操作與詳細資料",noAudit:"尚無操作記錄。",backups:"備份",backupLocation:"儲存位置",createNow:"立即建立",creating:"建立中…",backupStopNote:"為保持一致性，請安全停止伺服器後再備份。",validBackup:"完整性正常",invalidBackup:"需要檢查",restore:"還原",deleteBackup:"刪除備份",noBackups:"尚無備份。",backupCreated:"已建立 Palworld 備份",backupRestored:"已還原 Palworld 備份",backupDeleted:"已刪除備份",restoreConfirm:"還原「{name}」嗎？\n目前狀態將儲存為還原前備份。",deleteBackupConfirm:"刪除「{name}」嗎？" },
  ko: { serverFiles:"서버 파일",openWindows:"Windows에서 열기",newFile:"새 파일",newFolder:"새 폴더",upload:"업로드",sandboxNote:"접근 범위는 이 서버 폴더로 제한됩니다. 서버가 중지된 동안에만 파일을 변경할 수 있습니다.",parentFolder:"상위 폴더",emptyFolder:"이 폴더는 비어 있습니다.",download:"다운로드",rename:"이름 변경",delete:"삭제",unsaved:"저장 안 됨",saved:"저장됨",save:"저장",unsupportedEdit:"이 형식은 앱에서 편집할 수 없습니다. 다운로드하거나 Windows에서 열어 확인하세요.",selectFile:"파일을 선택하면 내용과 작업이 표시됩니다.",discardChanges:"저장하지 않은 변경을 버리고 다른 항목을 여시겠습니까?",newFilePrompt:"새 파일 이름",newFolderPrompt:"새 폴더 이름",renamePrompt:"새 이름",deleteConfirm:"“{name}”을(를) 영구 삭제하시겠습니까?\n이 작업은 취소할 수 없습니다.",uploadTitle:"서버에 추가할 파일 선택",downloadTitle:"파일 저장",accessLog:"접근 로그",searchAudit:"작업 및 세부 정보 검색",noAudit:"기록된 작업이 없습니다.",backups:"백업",backupLocation:"저장 위치",createNow:"지금 만들기",creating:"만드는 중…",backupStopNote:"일관성을 위해 서버를 안전하게 중지한 후 백업하세요.",validBackup:"무결성 정상",invalidBackup:"확인 필요",restore:"복원",deleteBackup:"백업 삭제",noBackups:"아직 백업이 없습니다.",backupCreated:"Palworld 백업을 만들었습니다",backupRestored:"Palworld 백업을 복원했습니다",backupDeleted:"백업을 삭제했습니다",restoreConfirm:"“{name}”을(를) 복원하시겠습니까?\n현재 상태는 복원 전 백업으로 저장됩니다.",deleteBackupConfirm:"“{name}”을(를) 삭제하시겠습니까?" },
  es: { serverFiles:"Archivos del servidor",openWindows:"Abrir en Windows",newFile:"Archivo nuevo",newFolder:"Carpeta nueva",upload:"Subir",sandboxNote:"El acceso está limitado a la carpeta de este servidor. Los archivos solo se pueden cambiar con el servidor detenido.",parentFolder:"Carpeta superior",emptyFolder:"Esta carpeta está vacía.",download:"Descargar",rename:"Cambiar nombre",delete:"Eliminar",unsaved:"Sin guardar",saved:"Guardado",save:"Guardar",unsupportedEdit:"Este formato no se puede editar en la aplicación. Descárgalo o ábrelo en Windows para revisarlo.",selectFile:"Selecciona un archivo para ver su contenido y acciones.",discardChanges:"¿Descartar los cambios sin guardar y abrir otro elemento?",newFilePrompt:"Nombre del archivo nuevo",newFolderPrompt:"Nombre de la carpeta nueva",renamePrompt:"Nombre nuevo",deleteConfirm:"¿Eliminar “{name}” permanentemente?\nEsta acción no se puede deshacer.",uploadTitle:"Selecciona un archivo para añadir al servidor",downloadTitle:"Guardar archivo",accessLog:"Registro de acceso",searchAudit:"Buscar acciones y detalles",noAudit:"No hay acciones registradas.",backups:"Copias de seguridad",backupLocation:"Ubicación",createNow:"Crear ahora",creating:"Creando…",backupStopNote:"Detén el servidor de forma segura antes de hacer una copia para mantener la coherencia.",validBackup:"Integridad correcta",invalidBackup:"Requiere revisión",restore:"Restaurar",deleteBackup:"Eliminar copia",noBackups:"Aún no hay copias de seguridad.",backupCreated:"Copia de Palworld creada",backupRestored:"Copia de Palworld restaurada",backupDeleted:"Copia eliminada",restoreConfirm:"¿Restaurar “{name}”?\nEl estado actual se guardará como copia previa.",deleteBackupConfirm:"¿Eliminar “{name}”?" },
  de: { serverFiles:"Serverdateien",openWindows:"In Windows öffnen",newFile:"Neue Datei",newFolder:"Neuer Ordner",upload:"Hochladen",sandboxNote:"Der Zugriff ist auf diesen Serverordner beschränkt. Dateien können nur bei gestopptem Server geändert werden.",parentFolder:"Übergeordneter Ordner",emptyFolder:"Dieser Ordner ist leer.",download:"Herunterladen",rename:"Umbenennen",delete:"Löschen",unsaved:"Nicht gespeichert",saved:"Gespeichert",save:"Speichern",unsupportedEdit:"Dieses Format kann nicht in der App bearbeitet werden. Lade es herunter oder öffne es in Windows.",selectFile:"Wähle eine Datei, um Inhalt und Aktionen anzuzeigen.",discardChanges:"Ungespeicherte Änderungen verwerfen und ein anderes Element öffnen?",newFilePrompt:"Neuer Dateiname",newFolderPrompt:"Neuer Ordnername",renamePrompt:"Neuer Name",deleteConfirm:"„{name}“ dauerhaft löschen?\nDies kann nicht rückgängig gemacht werden.",uploadTitle:"Datei zum Hinzufügen auswählen",downloadTitle:"Datei speichern",accessLog:"Zugriffsprotokoll",searchAudit:"Aktionen und Details durchsuchen",noAudit:"Keine Aktionen aufgezeichnet.",backups:"Sicherungen",backupLocation:"Speicherort",createNow:"Jetzt erstellen",creating:"Wird erstellt…",backupStopNote:"Stoppe den Server vor der Sicherung sicher, um Konsistenz zu gewährleisten.",validBackup:"Integrität OK",invalidBackup:"Prüfung nötig",restore:"Wiederherstellen",deleteBackup:"Sicherung löschen",noBackups:"Noch keine Sicherungen.",backupCreated:"Palworld-Sicherung erstellt",backupRestored:"Palworld-Sicherung wiederhergestellt",backupDeleted:"Sicherung gelöscht",restoreConfirm:"„{name}“ wiederherstellen?\nDer aktuelle Stand wird als Sicherung vor der Wiederherstellung gespeichert.",deleteBackupConfirm:"„{name}“ löschen?" },
  fr: { serverFiles:"Fichiers du serveur",openWindows:"Ouvrir dans Windows",newFile:"Nouveau fichier",newFolder:"Nouveau dossier",upload:"Téléverser",sandboxNote:"L’accès est limité au dossier de ce serveur. Les fichiers ne peuvent être modifiés que lorsque le serveur est arrêté.",parentFolder:"Dossier parent",emptyFolder:"Ce dossier est vide.",download:"Télécharger",rename:"Renommer",delete:"Supprimer",unsaved:"Non enregistré",saved:"Enregistré",save:"Enregistrer",unsupportedEdit:"Ce format ne peut pas être modifié dans l’application. Téléchargez-le ou ouvrez-le dans Windows.",selectFile:"Sélectionnez un fichier pour afficher son contenu et ses actions.",discardChanges:"Ignorer les modifications non enregistrées et ouvrir un autre élément ?",newFilePrompt:"Nom du nouveau fichier",newFolderPrompt:"Nom du nouveau dossier",renamePrompt:"Nouveau nom",deleteConfirm:"Supprimer définitivement « {name} » ?\nCette action est irréversible.",uploadTitle:"Sélectionner un fichier à ajouter",downloadTitle:"Enregistrer le fichier",accessLog:"Journal d’accès",searchAudit:"Rechercher les actions et détails",noAudit:"Aucune action enregistrée.",backups:"Sauvegardes",backupLocation:"Emplacement",createNow:"Créer maintenant",creating:"Création…",backupStopNote:"Arrêtez le serveur en toute sécurité avant la sauvegarde pour préserver la cohérence.",validBackup:"Intégrité OK",invalidBackup:"À vérifier",restore:"Restaurer",deleteBackup:"Supprimer la sauvegarde",noBackups:"Aucune sauvegarde pour le moment.",backupCreated:"Sauvegarde Palworld créée",backupRestored:"Sauvegarde Palworld restaurée",backupDeleted:"Sauvegarde supprimée",restoreConfirm:"Restaurer « {name} » ?\nL’état actuel sera conservé comme sauvegarde préalable.",deleteBackupConfirm:"Supprimer « {name} » ?" },
  "pt-BR": { serverFiles:"Arquivos do servidor",openWindows:"Abrir no Windows",newFile:"Novo arquivo",newFolder:"Nova pasta",upload:"Enviar",sandboxNote:"O acesso é limitado à pasta deste servidor. Os arquivos só podem ser alterados com o servidor parado.",parentFolder:"Pasta superior",emptyFolder:"Esta pasta está vazia.",download:"Baixar",rename:"Renomear",delete:"Excluir",unsaved:"Não salvo",saved:"Salvo",save:"Salvar",unsupportedEdit:"Este formato não pode ser editado no aplicativo. Baixe-o ou abra-o no Windows para conferir.",selectFile:"Selecione um arquivo para ver o conteúdo e as ações.",discardChanges:"Descartar alterações não salvas e abrir outro item?",newFilePrompt:"Nome do novo arquivo",newFolderPrompt:"Nome da nova pasta",renamePrompt:"Novo nome",deleteConfirm:"Excluir “{name}” permanentemente?\nEsta ação não pode ser desfeita.",uploadTitle:"Selecione um arquivo para adicionar ao servidor",downloadTitle:"Salvar arquivo",accessLog:"Log de acesso",searchAudit:"Pesquisar ações e detalhes",noAudit:"Nenhuma ação foi registrada.",backups:"Backups",backupLocation:"Local",createNow:"Criar agora",creating:"Criando…",backupStopNote:"Pare o servidor com segurança antes do backup para manter a consistência.",validBackup:"Integridade OK",invalidBackup:"Precisa de revisão",restore:"Restaurar",deleteBackup:"Excluir backup",noBackups:"Ainda não há backups.",backupCreated:"Backup do Palworld criado",backupRestored:"Backup do Palworld restaurado",backupDeleted:"Backup excluído",restoreConfirm:"Restaurar “{name}”?\nO estado atual será salvo como backup anterior à restauração.",deleteBackupConfirm:"Excluir “{name}”?" },
};

export function serverManagerText(locale: AppLocale, key: Key, values: Record<string, string> = {}) {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value), copies[locale][key]);
}
