import type { Locale } from "./locale";

export interface BuildEnvironmentText {
  nav: string; title: string; intro: string; ready: string; incomplete: string; unsupported: string;
  tools: string; available: string; unavailable: string; version: string; host: string; expected: string;
  rustTarget: string; installed: string; missing: string; issues: string; noIssues: string; privacy: string;
}

const copy: Record<Locale, BuildEnvironmentText> = {
  ja: { nav: "ビルド環境", title: "ビルド環境センター", intro: "このPCのNode、npm、Rust、Cargo、rustup、Windows x64ターゲットをローカルで確認します。", ready: "ビルド準備完了", incomplete: "不足しているツールがあります", unsupported: "未対応のホスト環境", tools: "開発ツール", available: "利用可能", unavailable: "利用不可", version: "バージョン", host: "現在のホスト", expected: "必要なホスト", rustTarget: "Rustターゲット", installed: "インストール済み", missing: "未インストール", issues: "検出した問題", noIssues: "Windows x64ビルドに必要な環境が揃っています。", privacy: "バージョンとアーキテクチャだけを表示し、環境変数や絶対パスは収集しません。" },
  en: { nav: "Build environment", title: "Build Environment Center", intro: "Checks Node, npm, Rust, Cargo, rustup, and the Windows x64 target locally on this PC.", ready: "Ready to build", incomplete: "Required tools are missing", unsupported: "Unsupported host environment", tools: "Development tools", available: "Available", unavailable: "Unavailable", version: "Version", host: "Current host", expected: "Required host", rustTarget: "Rust target", installed: "Installed", missing: "Not installed", issues: "Detected issues", noIssues: "Everything required for Windows x64 builds is available.", privacy: "Only versions and architecture are shown. Environment variables and absolute paths are not collected." },
  "zh-CN": { nav: "构建环境", title: "构建环境中心", intro: "在本机检查 Node、npm、Rust、Cargo、rustup 和 Windows x64 目标。", ready: "构建准备就绪", incomplete: "缺少必需工具", unsupported: "不支持的主机环境", tools: "开发工具", available: "可用", unavailable: "不可用", version: "版本", host: "当前主机", expected: "所需主机", rustTarget: "Rust 目标", installed: "已安装", missing: "未安装", issues: "检测到的问题", noIssues: "Windows x64 构建所需环境已齐全。", privacy: "仅显示版本和架构，不收集环境变量或绝对路径。" },
  "zh-TW": { nav: "建置環境", title: "建置環境中心", intro: "在本機檢查 Node、npm、Rust、Cargo、rustup 與 Windows x64 目標。", ready: "建置準備完成", incomplete: "缺少必要工具", unsupported: "不支援的主機環境", tools: "開發工具", available: "可用", unavailable: "不可用", version: "版本", host: "目前主機", expected: "必要主機", rustTarget: "Rust 目標", installed: "已安裝", missing: "未安裝", issues: "偵測到的問題", noIssues: "Windows x64 建置所需環境已齊全。", privacy: "僅顯示版本與架構，不收集環境變數或絕對路徑。" },
  ko: { nav: "빌드 환경", title: "빌드 환경 센터", intro: "이 PC에서 Node, npm, Rust, Cargo, rustup 및 Windows x64 대상을 로컬로 확인합니다.", ready: "빌드 준비 완료", incomplete: "필수 도구가 부족합니다", unsupported: "지원하지 않는 호스트 환경", tools: "개발 도구", available: "사용 가능", unavailable: "사용 불가", version: "버전", host: "현재 호스트", expected: "필요한 호스트", rustTarget: "Rust 대상", installed: "설치됨", missing: "설치되지 않음", issues: "감지된 문제", noIssues: "Windows x64 빌드에 필요한 환경이 모두 준비되었습니다.", privacy: "버전과 아키텍처만 표시하며 환경 변수나 절대 경로는 수집하지 않습니다." },
  es: { nav: "Entorno de compilación", title: "Centro del entorno de compilación", intro: "Comprueba localmente Node, npm, Rust, Cargo, rustup y el destino Windows x64.", ready: "Listo para compilar", incomplete: "Faltan herramientas necesarias", unsupported: "Entorno anfitrión no compatible", tools: "Herramientas de desarrollo", available: "Disponible", unavailable: "No disponible", version: "Versión", host: "Host actual", expected: "Host necesario", rustTarget: "Destino Rust", installed: "Instalado", missing: "No instalado", issues: "Problemas detectados", noIssues: "Está disponible todo lo necesario para compilar Windows x64.", privacy: "Solo se muestran versiones y arquitectura; no se recopilan variables ni rutas absolutas." },
  de: { nav: "Build-Umgebung", title: "Build-Umgebungscenter", intro: "Prüft Node, npm, Rust, Cargo, rustup und das Windows-x64-Ziel lokal auf diesem PC.", ready: "Buildbereit", incomplete: "Erforderliche Werkzeuge fehlen", unsupported: "Nicht unterstützte Hostumgebung", tools: "Entwicklungswerkzeuge", available: "Verfügbar", unavailable: "Nicht verfügbar", version: "Version", host: "Aktueller Host", expected: "Erforderlicher Host", rustTarget: "Rust-Ziel", installed: "Installiert", missing: "Nicht installiert", issues: "Erkannte Probleme", noIssues: "Alles für Windows-x64-Builds ist verfügbar.", privacy: "Nur Versionen und Architektur werden angezeigt; Umgebungsvariablen und absolute Pfade werden nicht erfasst." },
  fr: { nav: "Environnement de build", title: "Centre de l’environnement de build", intro: "Vérifie localement Node, npm, Rust, Cargo, rustup et la cible Windows x64.", ready: "Prêt à compiler", incomplete: "Des outils requis manquent", unsupported: "Environnement hôte non pris en charge", tools: "Outils de développement", available: "Disponible", unavailable: "Indisponible", version: "Version", host: "Hôte actuel", expected: "Hôte requis", rustTarget: "Cible Rust", installed: "Installée", missing: "Non installée", issues: "Problèmes détectés", noIssues: "Tout le nécessaire pour compiler Windows x64 est disponible.", privacy: "Seules les versions et l’architecture sont affichées; aucune variable ni chemin absolu n’est collecté." },
  "pt-BR": { nav: "Ambiente de build", title: "Central do ambiente de build", intro: "Verifica localmente Node, npm, Rust, Cargo, rustup e o alvo Windows x64.", ready: "Pronto para compilar", incomplete: "Ferramentas obrigatórias ausentes", unsupported: "Ambiente host incompatível", tools: "Ferramentas de desenvolvimento", available: "Disponível", unavailable: "Indisponível", version: "Versão", host: "Host atual", expected: "Host necessário", rustTarget: "Alvo Rust", installed: "Instalado", missing: "Não instalado", issues: "Problemas detectados", noIssues: "Tudo o que é necessário para builds Windows x64 está disponível.", privacy: "Somente versões e arquitetura são exibidas; variáveis e caminhos absolutos não são coletados." },
};

export const buildEnvironmentText = (locale: Locale) => copy[locale];
