import type { Locale } from "./locale";

export interface CapabilitySecurityText {
  nav: string; title: string; intro: string; verified: string; violation: string; missing: string; invalid: string;
  permissions: string; allowed: string; capabilityWindows: string; configuredWindows: string; directives: string;
  identities: string; capabilityId: string; appId: string; sourceFiles: string; issues: string; noIssues: string; readOnly: string;
}

const copy: Record<Locale, CapabilitySecurityText> = {
  ja: { nav: "権限セキュリティ", title: "権限セキュリティセンター", intro: "Developer Tools自身のTauri権限、対象ウィンドウ、CSPを固定の最小許可リストと照合します。", verified: "最小権限を確認済み", violation: "許可範囲の拡大を検出", missing: "設定ファイルがありません", invalid: "設定を解析できません", permissions: "Tauri権限", allowed: "許可済み", capabilityWindows: "Capability対象", configuredWindows: "構成済みウィンドウ", directives: "CSPディレクティブ", identities: "アプリ識別子", capabilityId: "Capability ID", appId: "App ID", sourceFiles: "検査元ファイル", issues: "検出した問題", noIssues: "余分な権限・ウィンドウ・CSPソースはありません。", readOnly: "このセンターは設定を変更しません。" },
  en: { nav: "Permission security", title: "Capability Security Center", intro: "Compares Developer Tools' Tauri permissions, target windows, and CSP with an exact least-privilege allowlist.", verified: "Least privilege verified", violation: "Permission expansion detected", missing: "Configuration file missing", invalid: "Configuration cannot be parsed", permissions: "Tauri permissions", allowed: "Allowed", capabilityWindows: "Capability windows", configuredWindows: "Configured windows", directives: "CSP directives", identities: "Application identifiers", capabilityId: "Capability ID", appId: "App ID", sourceFiles: "Inspected files", issues: "Detected issues", noIssues: "No extra permissions, windows, or CSP sources were found.", readOnly: "This center does not change configuration." },
  "zh-CN": { nav: "权限安全", title: "权限安全中心", intro: "将开发者工具的 Tauri 权限、窗口和 CSP 与最小权限白名单进行精确比较。", verified: "已验证最小权限", violation: "检测到权限扩展", missing: "配置文件缺失", invalid: "无法解析配置", permissions: "Tauri 权限", allowed: "已允许", capabilityWindows: "Capability 窗口", configuredWindows: "已配置窗口", directives: "CSP 指令", identities: "应用标识符", capabilityId: "Capability ID", appId: "App ID", sourceFiles: "检查文件", issues: "检测到的问题", noIssues: "未发现额外权限、窗口或 CSP 来源。", readOnly: "此中心不会更改配置。" },
  "zh-TW": { nav: "權限安全", title: "權限安全中心", intro: "將開發者工具的 Tauri 權限、視窗與 CSP 和最小權限白名單精確比對。", verified: "已驗證最小權限", violation: "偵測到權限擴張", missing: "缺少設定檔", invalid: "無法解析設定", permissions: "Tauri 權限", allowed: "已允許", capabilityWindows: "Capability 視窗", configuredWindows: "已設定視窗", directives: "CSP 指令", identities: "應用程式識別碼", capabilityId: "Capability ID", appId: "App ID", sourceFiles: "檢查檔案", issues: "偵測到的問題", noIssues: "未發現額外權限、視窗或 CSP 來源。", readOnly: "此中心不會變更設定。" },
  ko: { nav: "권한 보안", title: "권한 보안 센터", intro: "Developer Tools의 Tauri 권한, 대상 창, CSP를 최소 권한 허용 목록과 정확히 비교합니다.", verified: "최소 권한 확인 완료", violation: "권한 확장 감지", missing: "설정 파일 없음", invalid: "설정을 해석할 수 없음", permissions: "Tauri 권한", allowed: "허용됨", capabilityWindows: "Capability 창", configuredWindows: "구성된 창", directives: "CSP 지시문", identities: "앱 식별자", capabilityId: "Capability ID", appId: "App ID", sourceFiles: "검사 파일", issues: "감지된 문제", noIssues: "추가 권한, 창 또는 CSP 소스가 없습니다.", readOnly: "이 센터는 설정을 변경하지 않습니다." },
  es: { nav: "Seguridad de permisos", title: "Centro de seguridad de capacidades", intro: "Compara los permisos Tauri, ventanas y CSP con una lista exacta de privilegios mínimos.", verified: "Privilegios mínimos verificados", violation: "Ampliación de permisos detectada", missing: "Falta el archivo de configuración", invalid: "No se puede analizar la configuración", permissions: "Permisos Tauri", allowed: "Permitido", capabilityWindows: "Ventanas de capacidad", configuredWindows: "Ventanas configuradas", directives: "Directivas CSP", identities: "Identificadores", capabilityId: "ID de capacidad", appId: "ID de aplicación", sourceFiles: "Archivos inspeccionados", issues: "Problemas detectados", noIssues: "No se encontraron permisos, ventanas ni fuentes CSP adicionales.", readOnly: "Este centro no modifica la configuración." },
  de: { nav: "Berechtigungsschutz", title: "Capability-Sicherheitscenter", intro: "Vergleicht Tauri-Berechtigungen, Fenster und CSP exakt mit einer Least-Privilege-Zulassungsliste.", verified: "Minimale Rechte bestätigt", violation: "Berechtigungserweiterung erkannt", missing: "Konfigurationsdatei fehlt", invalid: "Konfiguration nicht lesbar", permissions: "Tauri-Berechtigungen", allowed: "Zugelassen", capabilityWindows: "Capability-Fenster", configuredWindows: "Konfigurierte Fenster", directives: "CSP-Direktiven", identities: "App-Kennungen", capabilityId: "Capability-ID", appId: "App-ID", sourceFiles: "Geprüfte Dateien", issues: "Erkannte Probleme", noIssues: "Keine zusätzlichen Berechtigungen, Fenster oder CSP-Quellen gefunden.", readOnly: "Dieses Center ändert keine Konfiguration." },
  fr: { nav: "Sécurité des permissions", title: "Centre de sécurité des capacités", intro: "Compare exactement les permissions Tauri, les fenêtres et la CSP à une liste d'autorisation minimale.", verified: "Privilèges minimaux vérifiés", violation: "Extension des permissions détectée", missing: "Fichier de configuration absent", invalid: "Configuration illisible", permissions: "Permissions Tauri", allowed: "Autorisé", capabilityWindows: "Fenêtres de capacité", configuredWindows: "Fenêtres configurées", directives: "Directives CSP", identities: "Identifiants", capabilityId: "ID de capacité", appId: "ID d'application", sourceFiles: "Fichiers inspectés", issues: "Problèmes détectés", noIssues: "Aucune permission, fenêtre ou source CSP supplémentaire.", readOnly: "Ce centre ne modifie pas la configuration." },
  "pt-BR": { nav: "Segurança de permissões", title: "Central de segurança de capacidades", intro: "Compara permissões Tauri, janelas e CSP com uma lista exata de privilégios mínimos.", verified: "Privilégio mínimo verificado", violation: "Expansão de permissões detectada", missing: "Arquivo de configuração ausente", invalid: "Não foi possível analisar a configuração", permissions: "Permissões Tauri", allowed: "Permitido", capabilityWindows: "Janelas de capacidade", configuredWindows: "Janelas configuradas", directives: "Diretivas CSP", identities: "Identificadores", capabilityId: "ID da capacidade", appId: "ID do aplicativo", sourceFiles: "Arquivos inspecionados", issues: "Problemas detectados", noIssues: "Nenhuma permissão, janela ou fonte CSP extra foi encontrada.", readOnly: "Esta central não altera a configuração." },
};

export const capabilitySecurityText = (locale: Locale) => copy[locale];
