import type { Locale } from "./locale";

export interface DeveloperUpdateCopy {
  nav: string;
  kicker: string;
  title: string;
  intro: string;
  currentVersion: string;
  autoCheck: string;
  autoCheckHelp: string;
  officialFeed: string;
  officialFeedHelp: string;
  check: string;
  checking: string;
  upToDate: string;
  available: string;
  releaseNotes: string;
  publishedAt: string;
  reviewConsent: string;
  reviewConsentHelp: string;
  install: string;
  installing: string;
  downloadProgress: string;
  downloadProgressUnknown: string;
  verifying: string;
  browserOnly: string;
  failureSafe: string;
  settingsSaved: string;
  startupAvailable: string;
  updateStarted: string;
  errorTitle: string;
  errorFeedInvalid: string;
  errorCheckFailed: string;
  errorDownloadFailed: string;
  errorInstallFailed: string;
  errorNotAvailable: string;
  errorVersionChanged: string;
  errorNotConfirmed: string;
  errorNativeOnly: string;
  errorUnknown: string;
  privacy: string;
}

interface DeveloperCompletionCopy {
  completionKicker: string;
  completionTitle: string;
  completionDescription: string;
  completionMaintenance: string;
}

const copies: Record<Locale, DeveloperUpdateCopy> = {
  ja: {
    nav: "Developer Toolsの更新", kicker: "D31 · FINAL RELEASE", title: "Developer Toolsを安全に更新", intro: "専用の公式HTTPSフィードだけを確認し、更新内容を表示して、あなたが許可した場合だけダウンロードと署名検証を行います。", currentVersion: "現在のバージョン", autoCheck: "起動時に更新を確認", autoCheckHelp: "確認だけを行います。自動ダウンロードや自動インストールはしません。", officialFeed: "Developer Tools専用公式フィード", officialFeedHelp: "一般向けMinecraft Server Hubの更新フィードとは完全に分離されています。", check: "更新を確認", checking: "更新を確認しています…", upToDate: "最新バージョンです", available: "新しいバージョンがあります", releaseNotes: "更新内容", publishedAt: "公開日時", reviewConsent: "バージョンと更新内容を確認し、この更新のダウンロードと適用を許可します", reviewConsentHelp: "署名検証に失敗した場合は適用せず、現在のアプリを残します。", install: "ダウンロード・検証して更新", installing: "更新を準備しています…", downloadProgress: "{total}中{downloaded}をダウンロード", downloadProgressUnknown: "{downloaded}をダウンロード", verifying: "署名を検証し、更新プログラムを準備しています…", browserOnly: "更新の適用はWindowsへインストールしたDeveloper Toolsでのみ利用できます。", failureSafe: "確認、ダウンロード、署名検証、適用のいずれかに失敗した場合、現在のアプリを維持します。", settingsSaved: "起動時の更新確認設定を保存しました。", startupAvailable: "Developer Tools {version}があります。内容を確認してください。", updateStarted: "署名検証済み更新の適用を開始しました。", errorTitle: "更新を完了できませんでした", errorFeedInvalid: "公式更新フィードの設定が正しくありません。", errorCheckFailed: "公式更新フィードを確認できませんでした。", errorDownloadFailed: "更新ファイルをダウンロードできませんでした。", errorInstallFailed: "署名検証または更新の適用に失敗しました。", errorNotAvailable: "利用できる更新がありません。もう一度確認してください。", errorVersionChanged: "確認後にバージョンが変わりました。更新内容をもう一度確認してください。", errorNotConfirmed: "更新内容への明示的な許可が必要です。", errorNativeOnly: "インストール済みWindowsアプリでのみ更新できます。", errorUnknown: "更新処理で予期しない問題が発生しました。", privacy: "ワークスペース、検査履歴、ライセンス台帳は更新フィードへ送信しません。",
  },
  en: {
    nav: "Developer Tools update", kicker: "D31 · FINAL RELEASE", title: "Update Developer Tools safely", intro: "Check only the dedicated official HTTPS feed, review the release, and download and verify it only after you approve.", currentVersion: "Current version", autoCheck: "Check for updates at startup", autoCheckHelp: "This checks only. It never downloads or installs automatically.", officialFeed: "Official Developer Tools feed", officialFeedHelp: "This is completely separate from the consumer Minecraft Server Hub update feed.", check: "Check for updates", checking: "Checking for updates…", upToDate: "You are up to date", available: "A new version is available", releaseNotes: "Release notes", publishedAt: "Published", reviewConsent: "I reviewed the version and release notes and approve downloading and applying this update", reviewConsentHelp: "A failed signature check leaves the currently installed app unchanged.", install: "Download, verify, and update", installing: "Preparing the update…", downloadProgress: "Downloaded {downloaded} of {total}", downloadProgressUnknown: "Downloaded {downloaded}", verifying: "Verifying the signature and preparing the updater…", browserOnly: "Applying updates is available only in the installed Windows Developer Tools app.", failureSafe: "If checking, downloading, signature verification, or applying fails, the current app is kept.", settingsSaved: "Startup update preference saved.", startupAvailable: "Developer Tools {version} is available. Review it before updating.", updateStarted: "The verified update is being applied.", errorTitle: "The update could not be completed", errorFeedInvalid: "The official update feed configuration is invalid.", errorCheckFailed: "The official update feed could not be checked.", errorDownloadFailed: "The update file could not be downloaded.", errorInstallFailed: "Signature verification or update installation failed.", errorNotAvailable: "No update is available. Check again.", errorVersionChanged: "The version changed after review. Review the release again.", errorNotConfirmed: "Explicit approval of the release is required.", errorNativeOnly: "Updates are available only in the installed Windows app.", errorUnknown: "An unexpected update error occurred.", privacy: "The workspace, inspection history, and license ledger are never sent to the update feed.",
  },
  "zh-CN": {
    nav: "Developer Tools 更新", kicker: "D31 · 正式完成版", title: "安全更新 Developer Tools", intro: "仅检查专用官方 HTTPS 更新源，显示更新内容，并且只在您允许后下载和验证签名。", currentVersion: "当前版本", autoCheck: "启动时检查更新", autoCheckHelp: "仅进行检查，不会自动下载或安装。", officialFeed: "Developer Tools 专用官方更新源", officialFeedHelp: "与普通 Minecraft Server Hub 的更新源完全分离。", check: "检查更新", checking: "正在检查更新…", upToDate: "已是最新版本", available: "有新版本可用", releaseNotes: "更新内容", publishedAt: "发布时间", reviewConsent: "我已确认版本和更新内容，并允许下载和应用此更新", reviewConsentHelp: "签名验证失败时不会应用，并保留当前应用。", install: "下载、验证并更新", installing: "正在准备更新…", downloadProgress: "已下载 {downloaded} / {total}", downloadProgressUnknown: "已下载 {downloaded}", verifying: "正在验证签名并准备更新程序…", browserOnly: "只能在已安装的 Windows Developer Tools 应用中应用更新。", failureSafe: "检查、下载、签名验证或应用失败时会保留当前应用。", settingsSaved: "已保存启动时更新检查设置。", startupAvailable: "Developer Tools {version} 可用，请先查看内容。", updateStarted: "正在应用已验证的更新。", errorTitle: "无法完成更新", errorFeedInvalid: "官方更新源配置无效。", errorCheckFailed: "无法检查官方更新源。", errorDownloadFailed: "无法下载更新文件。", errorInstallFailed: "签名验证或更新安装失败。", errorNotAvailable: "没有可用更新，请重新检查。", errorVersionChanged: "确认后版本发生变化，请重新查看。", errorNotConfirmed: "必须明确允许此更新。", errorNativeOnly: "只能在已安装的 Windows 应用中更新。", errorUnknown: "更新时发生意外错误。", privacy: "工作区、检查历史和许可证账本不会发送到更新源。",
  },
  "zh-TW": {
    nav: "Developer Tools 更新", kicker: "D31 · 正式完成版", title: "安全更新 Developer Tools", intro: "只檢查專用官方 HTTPS 來源，顯示更新內容，並只在您允許後下載及驗證簽章。", currentVersion: "目前版本", autoCheck: "啟動時檢查更新", autoCheckHelp: "只會檢查，不會自動下載或安裝。", officialFeed: "Developer Tools 專用官方來源", officialFeedHelp: "與一般 Minecraft Server Hub 更新來源完全分離。", check: "檢查更新", checking: "正在檢查更新…", upToDate: "已是最新版本", available: "有新版本可用", releaseNotes: "更新內容", publishedAt: "發布時間", reviewConsent: "我已確認版本和更新內容，並允許下載與套用此更新", reviewConsentHelp: "簽章驗證失敗時不會套用，並保留目前應用程式。", install: "下載、驗證並更新", installing: "正在準備更新…", downloadProgress: "已下載 {downloaded} / {total}", downloadProgressUnknown: "已下載 {downloaded}", verifying: "正在驗證簽章並準備更新程式…", browserOnly: "只能在已安裝的 Windows Developer Tools 應用程式套用更新。", failureSafe: "檢查、下載、簽章驗證或套用失敗時會保留目前應用程式。", settingsSaved: "已儲存啟動時更新檢查設定。", startupAvailable: "Developer Tools {version} 可用，請先查看內容。", updateStarted: "正在套用已驗證的更新。", errorTitle: "無法完成更新", errorFeedInvalid: "官方更新來源設定無效。", errorCheckFailed: "無法檢查官方更新來源。", errorDownloadFailed: "無法下載更新檔案。", errorInstallFailed: "簽章驗證或更新安裝失敗。", errorNotAvailable: "沒有可用更新，請重新檢查。", errorVersionChanged: "確認後版本已變更，請重新查看。", errorNotConfirmed: "必須明確允許此更新。", errorNativeOnly: "只能在已安裝的 Windows 應用程式更新。", errorUnknown: "更新時發生未預期的錯誤。", privacy: "工作區、檢查歷史和授權帳本不會傳送至更新來源。",
  },
  ko: {
    nav: "Developer Tools 업데이트", kicker: "D31 · 최종 릴리스", title: "Developer Tools를 안전하게 업데이트", intro: "전용 공식 HTTPS 피드만 확인하고 변경 내용을 표시한 뒤 사용자가 허용한 경우에만 다운로드하고 서명을 검증합니다.", currentVersion: "현재 버전", autoCheck: "시작할 때 업데이트 확인", autoCheckHelp: "확인만 하며 자동 다운로드나 설치는 하지 않습니다.", officialFeed: "Developer Tools 전용 공식 피드", officialFeedHelp: "일반 Minecraft Server Hub 업데이트 피드와 완전히 분리되어 있습니다.", check: "업데이트 확인", checking: "업데이트 확인 중…", upToDate: "최신 버전입니다", available: "새 버전을 사용할 수 있습니다", releaseNotes: "업데이트 내용", publishedAt: "게시일", reviewConsent: "버전과 변경 내용을 확인했으며 이 업데이트의 다운로드와 적용을 허용합니다", reviewConsentHelp: "서명 검증에 실패하면 적용하지 않고 현재 앱을 유지합니다.", install: "다운로드, 검증 및 업데이트", installing: "업데이트 준비 중…", downloadProgress: "{total} 중 {downloaded} 다운로드", downloadProgressUnknown: "{downloaded} 다운로드", verifying: "서명을 검증하고 업데이트 프로그램을 준비하는 중…", browserOnly: "설치된 Windows Developer Tools 앱에서만 업데이트를 적용할 수 있습니다.", failureSafe: "확인, 다운로드, 서명 검증 또는 적용에 실패하면 현재 앱을 유지합니다.", settingsSaved: "시작 시 업데이트 확인 설정을 저장했습니다.", startupAvailable: "Developer Tools {version}을 사용할 수 있습니다. 먼저 내용을 확인하세요.", updateStarted: "검증된 업데이트를 적용하고 있습니다.", errorTitle: "업데이트를 완료할 수 없습니다", errorFeedInvalid: "공식 업데이트 피드 설정이 잘못되었습니다.", errorCheckFailed: "공식 업데이트 피드를 확인할 수 없습니다.", errorDownloadFailed: "업데이트 파일을 다운로드할 수 없습니다.", errorInstallFailed: "서명 검증 또는 업데이트 설치에 실패했습니다.", errorNotAvailable: "사용 가능한 업데이트가 없습니다. 다시 확인하세요.", errorVersionChanged: "확인 후 버전이 변경되었습니다. 다시 검토하세요.", errorNotConfirmed: "업데이트에 대한 명시적 허용이 필요합니다.", errorNativeOnly: "설치된 Windows 앱에서만 업데이트할 수 있습니다.", errorUnknown: "업데이트 중 예기치 않은 오류가 발생했습니다.", privacy: "워크스페이스, 검사 기록, 라이선스 원장은 업데이트 피드로 전송되지 않습니다.",
  },
  es: {
    nav: "Actualización de Developer Tools", kicker: "D31 · VERSIÓN FINAL", title: "Actualizar Developer Tools de forma segura", intro: "Comprueba solo el canal HTTPS oficial dedicado, muestra los cambios y descarga y verifica la firma únicamente con tu permiso.", currentVersion: "Versión actual", autoCheck: "Buscar actualizaciones al iniciar", autoCheckHelp: "Solo comprueba; nunca descarga ni instala automáticamente.", officialFeed: "Canal oficial de Developer Tools", officialFeedHelp: "Está completamente separado del canal de Minecraft Server Hub para usuarios.", check: "Buscar actualizaciones", checking: "Buscando actualizaciones…", upToDate: "Está actualizado", available: "Hay una nueva versión", releaseNotes: "Notas de la versión", publishedAt: "Publicado", reviewConsent: "He revisado la versión y las notas y autorizo descargar y aplicar esta actualización", reviewConsentHelp: "Si falla la firma, no se aplica y se conserva la aplicación actual.", install: "Descargar, verificar y actualizar", installing: "Preparando la actualización…", downloadProgress: "Descargado {downloaded} de {total}", downloadProgressUnknown: "Descargado {downloaded}", verifying: "Verificando la firma y preparando el actualizador…", browserOnly: "Solo la aplicación Developer Tools instalada en Windows puede aplicar actualizaciones.", failureSafe: "Si falla la comprobación, descarga, firma o aplicación, se conserva la aplicación actual.", settingsSaved: "Preferencia de comprobación al inicio guardada.", startupAvailable: "Developer Tools {version} está disponible. Revísala antes de actualizar.", updateStarted: "Se está aplicando la actualización verificada.", errorTitle: "No se pudo completar la actualización", errorFeedInvalid: "La configuración del canal oficial no es válida.", errorCheckFailed: "No se pudo comprobar el canal oficial.", errorDownloadFailed: "No se pudo descargar el archivo de actualización.", errorInstallFailed: "Falló la firma o la instalación.", errorNotAvailable: "No hay ninguna actualización disponible.", errorVersionChanged: "La versión cambió tras la revisión. Revísala de nuevo.", errorNotConfirmed: "Se requiere autorización explícita.", errorNativeOnly: "Solo se puede actualizar en la aplicación instalada de Windows.", errorUnknown: "Se produjo un error de actualización inesperado.", privacy: "El espacio de trabajo, el historial y el registro de licencias no se envían al canal.",
  },
  de: {
    nav: "Developer-Tools-Update", kicker: "D31 · FINALE VERSION", title: "Developer Tools sicher aktualisieren", intro: "Es wird nur der eigene offizielle HTTPS-Feed geprüft. Download und Signaturprüfung erfolgen erst nach Ihrer Freigabe.", currentVersion: "Aktuelle Version", autoCheck: "Beim Start nach Updates suchen", autoCheckHelp: "Es wird nur geprüft, niemals automatisch heruntergeladen oder installiert.", officialFeed: "Offizieller Developer-Tools-Feed", officialFeedHelp: "Vollständig vom normalen Minecraft-Server-Hub-Feed getrennt.", check: "Nach Updates suchen", checking: "Updates werden gesucht…", upToDate: "Aktuell", available: "Eine neue Version ist verfügbar", releaseNotes: "Versionshinweise", publishedAt: "Veröffentlicht", reviewConsent: "Ich habe Version und Hinweise geprüft und erlaube Download und Anwendung", reviewConsentHelp: "Bei fehlgeschlagener Signaturprüfung bleibt die aktuelle App unverändert.", install: "Herunterladen, prüfen und aktualisieren", installing: "Update wird vorbereitet…", downloadProgress: "{downloaded} von {total} heruntergeladen", downloadProgressUnknown: "{downloaded} heruntergeladen", verifying: "Signatur wird geprüft und Updater vorbereitet…", browserOnly: "Updates können nur in der installierten Windows-App angewendet werden.", failureSafe: "Bei Fehlern in Prüfung, Download, Signatur oder Anwendung bleibt die aktuelle App erhalten.", settingsSaved: "Starteinstellung gespeichert.", startupAvailable: "Developer Tools {version} ist verfügbar. Bitte zuerst prüfen.", updateStarted: "Das verifizierte Update wird angewendet.", errorTitle: "Update konnte nicht abgeschlossen werden", errorFeedInvalid: "Der offizielle Feed ist ungültig konfiguriert.", errorCheckFailed: "Der offizielle Feed konnte nicht geprüft werden.", errorDownloadFailed: "Die Updatedatei konnte nicht geladen werden.", errorInstallFailed: "Signaturprüfung oder Installation ist fehlgeschlagen.", errorNotAvailable: "Kein Update verfügbar.", errorVersionChanged: "Die Version hat sich geändert. Bitte erneut prüfen.", errorNotConfirmed: "Eine ausdrückliche Freigabe ist erforderlich.", errorNativeOnly: "Updates sind nur in der installierten Windows-App möglich.", errorUnknown: "Ein unerwarteter Updatefehler ist aufgetreten.", privacy: "Workspace, Prüfverlauf und Lizenzbuch werden nicht an den Feed gesendet.",
  },
  fr: {
    nav: "Mise à jour de Developer Tools", kicker: "D31 · VERSION FINALE", title: "Mettre Developer Tools à jour en sécurité", intro: "Vérifie uniquement le flux HTTPS officiel dédié, affiche les changements et ne télécharge et vérifie la signature qu’après votre accord.", currentVersion: "Version actuelle", autoCheck: "Vérifier au démarrage", autoCheckHelp: "Vérification uniquement, sans téléchargement ni installation automatique.", officialFeed: "Flux officiel Developer Tools", officialFeedHelp: "Entièrement séparé du flux Minecraft Server Hub grand public.", check: "Rechercher des mises à jour", checking: "Recherche en cours…", upToDate: "Application à jour", available: "Une nouvelle version est disponible", releaseNotes: "Notes de version", publishedAt: "Publication", reviewConsent: "J’ai vérifié la version et les notes et j’autorise le téléchargement et l’application", reviewConsentHelp: "En cas d’échec de signature, la version actuelle reste inchangée.", install: "Télécharger, vérifier et mettre à jour", installing: "Préparation de la mise à jour…", downloadProgress: "{downloaded} téléchargés sur {total}", downloadProgressUnknown: "{downloaded} téléchargés", verifying: "Vérification de la signature et préparation…", browserOnly: "Seule l’application Windows installée peut appliquer les mises à jour.", failureSafe: "En cas d’échec de vérification, téléchargement, signature ou application, la version actuelle est conservée.", settingsSaved: "Préférence de vérification au démarrage enregistrée.", startupAvailable: "Developer Tools {version} est disponible. Vérifiez-la avant la mise à jour.", updateStarted: "La mise à jour vérifiée est en cours d’application.", errorTitle: "La mise à jour n’a pas pu être terminée", errorFeedInvalid: "La configuration du flux officiel est invalide.", errorCheckFailed: "Le flux officiel n’a pas pu être vérifié.", errorDownloadFailed: "Le fichier de mise à jour n’a pas pu être téléchargé.", errorInstallFailed: "La signature ou l’installation a échoué.", errorNotAvailable: "Aucune mise à jour disponible.", errorVersionChanged: "La version a changé. Vérifiez-la de nouveau.", errorNotConfirmed: "Une autorisation explicite est requise.", errorNativeOnly: "Mise à jour disponible uniquement dans l’application Windows installée.", errorUnknown: "Une erreur inattendue s’est produite.", privacy: "L’espace de travail, l’historique et le registre des licences ne sont jamais envoyés au flux.",
  },
  "pt-BR": {
    nav: "Atualização do Developer Tools", kicker: "D31 · VERSÃO FINAL", title: "Atualizar o Developer Tools com segurança", intro: "Verifica apenas o feed HTTPS oficial dedicado, mostra as alterações e baixa e valida a assinatura somente após sua permissão.", currentVersion: "Versão atual", autoCheck: "Verificar atualizações ao iniciar", autoCheckHelp: "Apenas verifica; nunca baixa nem instala automaticamente.", officialFeed: "Feed oficial do Developer Tools", officialFeedHelp: "Totalmente separado do feed comum do Minecraft Server Hub.", check: "Verificar atualizações", checking: "Verificando atualizações…", upToDate: "Está atualizado", available: "Uma nova versão está disponível", releaseNotes: "Notas da versão", publishedAt: "Publicado", reviewConsent: "Revisei a versão e as notas e autorizo o download e a aplicação desta atualização", reviewConsentHelp: "Se a assinatura falhar, a atualização não é aplicada e o app atual é mantido.", install: "Baixar, verificar e atualizar", installing: "Preparando a atualização…", downloadProgress: "Baixado {downloaded} de {total}", downloadProgressUnknown: "Baixado {downloaded}", verifying: "Verificando a assinatura e preparando o atualizador…", browserOnly: "As atualizações só podem ser aplicadas no Developer Tools instalado no Windows.", failureSafe: "Se a verificação, download, assinatura ou aplicação falhar, o app atual será mantido.", settingsSaved: "Preferência de verificação na inicialização salva.", startupAvailable: "Developer Tools {version} está disponível. Revise antes de atualizar.", updateStarted: "A atualização verificada está sendo aplicada.", errorTitle: "Não foi possível concluir a atualização", errorFeedInvalid: "A configuração do feed oficial é inválida.", errorCheckFailed: "Não foi possível verificar o feed oficial.", errorDownloadFailed: "Não foi possível baixar o arquivo de atualização.", errorInstallFailed: "A assinatura ou instalação falhou.", errorNotAvailable: "Nenhuma atualização disponível.", errorVersionChanged: "A versão mudou após a revisão. Revise novamente.", errorNotConfirmed: "É necessária uma autorização explícita.", errorNativeOnly: "Atualizações disponíveis apenas no app instalado do Windows.", errorUnknown: "Ocorreu um erro inesperado de atualização.", privacy: "O workspace, o histórico e o registro de licenças nunca são enviados ao feed.",
  },
};

const completionCopies: Record<Locale, DeveloperCompletionCopy> = {
  ja: { completionKicker: "D31 · 完成版", completionTitle: "更新基盤の最終仕上げ", completionDescription: "署名付き更新、失敗時の現行版維持、専用HTTPSフィード、9言語表示を完成版の境界として固定しました。", completionMaintenance: "今後は不具合修正と互換性更新を中心に保守します。" },
  en: { completionKicker: "D31 · FINAL RELEASE", completionTitle: "Finalized update foundation", completionDescription: "Signed updates, failure-safe retention, the dedicated HTTPS feed, and nine-language UI are fixed as the release boundary.", completionMaintenance: "Future work focuses on fixes and compatibility maintenance." },
  "zh-CN": { completionKicker: "D31 · 正式完成版", completionTitle: "更新基础已最终完成", completionDescription: "已将签名更新、失败时保留当前版本、专用 HTTPS 更新源和九种语言界面固定为正式版边界。", completionMaintenance: "今后将以错误修复和兼容性维护为主。" },
  "zh-TW": { completionKicker: "D31 · 正式完成版", completionTitle: "更新基礎已最終完成", completionDescription: "已將簽署更新、失敗時保留目前版本、專用 HTTPS 來源及九種語言介面固定為正式版界線。", completionMaintenance: "今後將以錯誤修正與相容性維護為主。" },
  ko: { completionKicker: "D31 · 최종 릴리스", completionTitle: "업데이트 기반 최종 완성", completionDescription: "서명 업데이트, 실패 시 현재 버전 유지, 전용 HTTPS 피드, 9개 언어 UI를 정식 릴리스 경계로 고정했습니다.", completionMaintenance: "앞으로는 오류 수정과 호환성 유지 관리에 집중합니다." },
  es: { completionKicker: "D31 · VERSIÓN FINAL", completionTitle: "Base de actualización finalizada", completionDescription: "Las actualizaciones firmadas, la conservación ante fallos, el canal HTTPS dedicado y la interfaz en nueve idiomas quedan fijados como límite de la versión final.", completionMaintenance: "El trabajo futuro se centrará en correcciones y compatibilidad." },
  de: { completionKicker: "D31 · FINALE VERSION", completionTitle: "Update-Grundlage fertiggestellt", completionDescription: "Signierte Updates, Bestandsschutz bei Fehlern, der eigene HTTPS-Feed und die Oberfläche in neun Sprachen bilden die feste Release-Grenze.", completionMaintenance: "Künftig stehen Fehlerbehebungen und Kompatibilität im Mittelpunkt." },
  fr: { completionKicker: "D31 · VERSION FINALE", completionTitle: "Base de mise à jour finalisée", completionDescription: "Les mises à jour signées, la conservation en cas d’échec, le flux HTTPS dédié et l’interface en neuf langues définissent la version finale.", completionMaintenance: "La suite sera consacrée aux correctifs et à la compatibilité." },
  "pt-BR": { completionKicker: "D31 · VERSÃO FINAL", completionTitle: "Base de atualização finalizada", completionDescription: "Atualizações assinadas, preservação em caso de falha, feed HTTPS dedicado e interface em nove idiomas ficam definidos como limite da versão final.", completionMaintenance: "O trabalho futuro focará correções e compatibilidade." },
};

export const developerUpdateLocales: Record<Locale, DeveloperUpdateCopy & DeveloperCompletionCopy> = Object.fromEntries(
  Object.entries(copies).map(([locale, copy]) => [locale, { ...copy, ...completionCopies[locale as Locale] }]),
) as Record<Locale, DeveloperUpdateCopy & DeveloperCompletionCopy>;
export const developerUpdateText = (locale: Locale): DeveloperUpdateCopy & DeveloperCompletionCopy => developerUpdateLocales[locale];

