import type { Locale } from "./locale";
import type { SupplyChainChangeKind } from "./supplyChainDiff";

export interface SupplyChainDiffText {
  title: string; intro: string; noBaseline: string; noBaselineHint: string; saveBaseline: string; saved: string; baseline: string; current: string; remove: string; export: string; exporting: string; exported: string; canceled: string; failed: string; privacy: string; advisoryPending: string; noChanges: string; all: string; changes: string; packages: string; createdAt: string;
  categories: Record<SupplyChainChangeKind, string>;
  reasons: Record<string, string>;
}

const commonReasons = {
  "version-changed": "Version changed", "license-class-changed": "License class changed", "license-expression-changed": "License expression changed", "license-risk-increased": "License risk increased", "license-risk-decreased": "License risk decreased", "integrity-missing": "Integrity evidence missing", "integrity-restored": "Integrity evidence restored", "advisories-increased": "Known advisories increased", "advisories-decreased": "Known advisories decreased", "package-removed": "Package removed", "package-added": "Package added", "new-license-risk": "New license risk", "new-integrity-gap": "New integrity gap", "new-affected-package": "New affected package",
};

const copy: Record<Locale, SupplyChainDiffText> = {
  ja: { title: "サプライチェーン差分センター", intro: "保存した基準点と現在のロックファイルを比較し、更新・削除・ライセンス変化・リスク悪化を判定します。", noBaseline: "比較できる基準点がありません。", noBaselineHint: "現在の状態を明示的に保存すると、次回の検査で差分を確認できます。", saveBaseline: "現在を基準点として保存", saved: "基準点を保存しました。", baseline: "比較元", current: "現在", remove: "基準点を削除", export: "差分JSONを書き出す", exporting: "書き出し中…", exported: "差分を保存しました: {path}", canceled: "保存をキャンセルしました。", failed: "差分処理に失敗しました。", privacy: "端末内に最大8世代を保存します。絶対パス、配布元、整合性ハッシュ、ユーザー名は記録しません。", advisoryPending: "現在の脆弱性照会は未完了です。依存・ライセンス・整合性の差分は有効ですが、脆弱性差分は確定していません。", noChanges: "選択した分類に変更はありません。", all: "すべて", changes: "変更", packages: "パッケージ", createdAt: "保存日時", categories: { added: "追加", removed: "削除", updated: "更新", license: "ライセンス変更", "risk-regression": "リスク悪化", "risk-improvement": "リスク改善" }, reasons: { ...commonReasons, "version-changed": "バージョン変更", "license-class-changed": "ライセンス分類変更", "license-expression-changed": "ライセンス表記変更", "license-risk-increased": "ライセンスリスク上昇", "license-risk-decreased": "ライセンスリスク低下", "integrity-missing": "整合性証拠が欠落", "integrity-restored": "整合性証拠を復元", "advisories-increased": "既知の脆弱性が増加", "advisories-decreased": "既知の脆弱性が減少", "package-removed": "パッケージ削除", "package-added": "パッケージ追加", "new-license-risk": "新しいライセンスリスク", "new-integrity-gap": "新しい整合性不足", "new-affected-package": "新しい脆弱性対象" } },
  en: { title: "Supply-chain Diff Center", intro: "Compare a saved baseline with current lockfiles to identify updates, removals, license changes, and risk regressions.", noBaseline: "No baseline is available for comparison.", noBaselineHint: "Explicitly save the current state, then compare it after a future inspection.", saveBaseline: "Save current baseline", saved: "Baseline saved.", baseline: "Baseline", current: "Current", remove: "Remove baseline", export: "Export diff JSON", exporting: "Exporting…", exported: "Diff saved to {path}", canceled: "Save was canceled.", failed: "The diff operation failed.", privacy: "Up to eight generations stay on this device. Absolute paths, sources, integrity hashes, and user names are never stored.", advisoryPending: "The current vulnerability query is incomplete. Dependency, license, and integrity changes remain valid; vulnerability changes are not final.", noChanges: "No changes in the selected category.", all: "All", changes: "Changes", packages: "Packages", createdAt: "Saved at", categories: { added: "Added", removed: "Removed", updated: "Updated", license: "License change", "risk-regression": "Risk regression", "risk-improvement": "Risk improvement" }, reasons: commonReasons },
  "zh-CN": { title: "供应链差异中心", intro: "比较保存的基线与当前锁文件，识别更新、删除、许可证变化和风险上升。", noBaseline: "没有可比较的基线。", noBaselineHint: "请明确保存当前状态，以便在下次检查时比较。", saveBaseline: "保存当前基线", saved: "基线已保存。", baseline: "基线", current: "当前", remove: "删除基线", export: "导出差异 JSON", exporting: "正在导出…", exported: "差异已保存到 {path}", canceled: "已取消保存。", failed: "差异操作失败。", privacy: "最多在本机保存八代；不会记录绝对路径、来源、完整性哈希或用户名。", advisoryPending: "当前漏洞查询尚未完成。依赖、许可证和完整性差异仍有效，漏洞差异尚未确定。", noChanges: "所选分类没有变化。", all: "全部", changes: "变化", packages: "软件包", createdAt: "保存时间", categories: { added: "新增", removed: "删除", updated: "更新", license: "许可证变化", "risk-regression": "风险上升", "risk-improvement": "风险改善" }, reasons: commonReasons },
  "zh-TW": { title: "供應鏈差異中心", intro: "比較儲存的基準與目前鎖定檔，識別更新、移除、授權變更與風險升高。", noBaseline: "沒有可比較的基準。", noBaselineHint: "請明確儲存目前狀態，以便下次檢查時比較。", saveBaseline: "儲存目前基準", saved: "基準已儲存。", baseline: "基準", current: "目前", remove: "刪除基準", export: "匯出差異 JSON", exporting: "正在匯出…", exported: "差異已儲存至 {path}", canceled: "已取消儲存。", failed: "差異作業失敗。", privacy: "最多在本機保留八代；不記錄絕對路徑、來源、完整性雜湊或使用者名稱。", advisoryPending: "目前弱點查詢尚未完成。相依、授權與完整性差異仍有效，弱點差異尚未確定。", noChanges: "所選分類沒有變更。", all: "全部", changes: "變更", packages: "套件", createdAt: "儲存時間", categories: { added: "新增", removed: "移除", updated: "更新", license: "授權變更", "risk-regression": "風險升高", "risk-improvement": "風險改善" }, reasons: commonReasons },
  ko: { title: "공급망 차이 센터", intro: "저장한 기준과 현재 잠금 파일을 비교하여 업데이트, 삭제, 라이선스 변경 및 위험 증가를 찾습니다.", noBaseline: "비교할 기준이 없습니다.", noBaselineHint: "현재 상태를 명시적으로 저장하면 다음 검사에서 비교할 수 있습니다.", saveBaseline: "현재 기준 저장", saved: "기준을 저장했습니다.", baseline: "기준", current: "현재", remove: "기준 삭제", export: "차이 JSON 내보내기", exporting: "내보내는 중…", exported: "차이를 {path}에 저장했습니다", canceled: "저장을 취소했습니다.", failed: "차이 작업에 실패했습니다.", privacy: "최대 8세대를 이 장치에만 저장하며 절대 경로, 출처, 무결성 해시, 사용자 이름은 기록하지 않습니다.", advisoryPending: "현재 취약점 조회가 완료되지 않았습니다. 의존성, 라이선스, 무결성 차이는 유효하지만 취약점 차이는 확정되지 않았습니다.", noChanges: "선택한 범주에 변경이 없습니다.", all: "전체", changes: "변경", packages: "패키지", createdAt: "저장 시간", categories: { added: "추가", removed: "삭제", updated: "업데이트", license: "라이선스 변경", "risk-regression": "위험 증가", "risk-improvement": "위험 개선" }, reasons: commonReasons },
  es: { title: "Centro de diferencias de la cadena", intro: "Compara una línea base guardada con los archivos de bloqueo actuales para detectar actualizaciones, eliminaciones, cambios de licencia y regresiones de riesgo.", noBaseline: "No hay una línea base para comparar.", noBaselineHint: "Guarda explícitamente el estado actual y compáralo tras una inspección futura.", saveBaseline: "Guardar línea base actual", saved: "Línea base guardada.", baseline: "Línea base", current: "Actual", remove: "Eliminar línea base", export: "Exportar JSON de diferencias", exporting: "Exportando…", exported: "Diferencia guardada en {path}", canceled: "Se canceló el guardado.", failed: "Falló la operación de diferencias.", privacy: "Se guardan hasta ocho generaciones en este dispositivo. No se almacenan rutas absolutas, orígenes, hashes de integridad ni nombres de usuario.", advisoryPending: "La consulta de vulnerabilidades actual está incompleta. Los cambios de dependencias, licencias e integridad siguen siendo válidos; los de vulnerabilidades no son definitivos.", noChanges: "No hay cambios en la categoría seleccionada.", all: "Todo", changes: "Cambios", packages: "Paquetes", createdAt: "Guardado", categories: { added: "Añadido", removed: "Eliminado", updated: "Actualizado", license: "Cambio de licencia", "risk-regression": "Riesgo mayor", "risk-improvement": "Riesgo menor" }, reasons: commonReasons },
  de: { title: "Supply-Chain-Differenzzentrum", intro: "Vergleicht eine gespeicherte Basis mit aktuellen Lockdateien und erkennt Updates, Entfernungen, Lizenzänderungen und Risikoverschlechterungen.", noBaseline: "Keine Vergleichsbasis vorhanden.", noBaselineHint: "Aktuellen Stand ausdrücklich speichern und nach einer späteren Prüfung vergleichen.", saveBaseline: "Aktuelle Basis speichern", saved: "Basis gespeichert.", baseline: "Basis", current: "Aktuell", remove: "Basis entfernen", export: "Differenz-JSON exportieren", exporting: "Export läuft…", exported: "Differenz gespeichert: {path}", canceled: "Speichern abgebrochen.", failed: "Differenzvorgang fehlgeschlagen.", privacy: "Bis zu acht Generationen bleiben auf diesem Gerät. Absolute Pfade, Quellen, Integritäts-Hashes und Benutzernamen werden nie gespeichert.", advisoryPending: "Die aktuelle Schwachstellenabfrage ist unvollständig. Abhängigkeits-, Lizenz- und Integritätsänderungen sind gültig; Schwachstellenänderungen noch nicht endgültig.", noChanges: "Keine Änderungen in der gewählten Kategorie.", all: "Alle", changes: "Änderungen", packages: "Pakete", createdAt: "Gespeichert", categories: { added: "Hinzugefügt", removed: "Entfernt", updated: "Aktualisiert", license: "Lizenzänderung", "risk-regression": "Risiko gestiegen", "risk-improvement": "Risiko gesunken" }, reasons: commonReasons },
  fr: { title: "Centre de différences de la chaîne", intro: "Compare une référence enregistrée aux fichiers verrouillés actuels pour identifier mises à jour, suppressions, changements de licence et hausses de risque.", noBaseline: "Aucune référence disponible.", noBaselineHint: "Enregistrez explicitement l’état actuel puis comparez-le après une prochaine inspection.", saveBaseline: "Enregistrer la référence actuelle", saved: "Référence enregistrée.", baseline: "Référence", current: "Actuel", remove: "Supprimer la référence", export: "Exporter le JSON des différences", exporting: "Export…", exported: "Différence enregistrée dans {path}", canceled: "Enregistrement annulé.", failed: "L’opération de différence a échoué.", privacy: "Jusqu’à huit générations restent sur cet appareil. Aucun chemin absolu, source, hash d’intégrité ou nom d’utilisateur n’est stocké.", advisoryPending: "La requête de vulnérabilités actuelle est incomplète. Les différences de dépendance, licence et intégrité restent valides ; celles de vulnérabilité ne sont pas définitives.", noChanges: "Aucun changement dans la catégorie sélectionnée.", all: "Tout", changes: "Changements", packages: "Paquets", createdAt: "Enregistré", categories: { added: "Ajouté", removed: "Supprimé", updated: "Mis à jour", license: "Changement de licence", "risk-regression": "Risque accru", "risk-improvement": "Risque réduit" }, reasons: commonReasons },
  "pt-BR": { title: "Central de diferenças da cadeia", intro: "Compara uma linha de base salva com os lockfiles atuais para identificar atualizações, remoções, mudanças de licença e regressões de risco.", noBaseline: "Não há linha de base para comparação.", noBaselineHint: "Salve explicitamente o estado atual e compare após uma inspeção futura.", saveBaseline: "Salvar linha de base atual", saved: "Linha de base salva.", baseline: "Linha de base", current: "Atual", remove: "Remover linha de base", export: "Exportar JSON de diferenças", exporting: "Exportando…", exported: "Diferença salva em {path}", canceled: "O salvamento foi cancelado.", failed: "A operação de diferenças falhou.", privacy: "Até oito gerações ficam neste dispositivo. Caminhos absolutos, origens, hashes de integridade e nomes de usuário nunca são armazenados.", advisoryPending: "A consulta de vulnerabilidades atual está incompleta. As mudanças de dependência, licença e integridade continuam válidas; as de vulnerabilidade ainda não são finais.", noChanges: "Não há mudanças na categoria selecionada.", all: "Tudo", changes: "Mudanças", packages: "Pacotes", createdAt: "Salvo em", categories: { added: "Adicionado", removed: "Removido", updated: "Atualizado", license: "Mudança de licença", "risk-regression": "Risco maior", "risk-improvement": "Risco menor" }, reasons: commonReasons },
};

export const supplyChainDiffText = (locale: Locale) => copy[locale];
