import type { Locale } from "./locale";
import type { SupplyChainReviewStageId } from "./supplyChainReadiness";

export interface SupplyChainReadinessText {
  nav: string; title: string; intro: string; ready: string; review: string; blocked: string;
  blockers: string; warnings: string; digest: string; open: string; privacy: string;
  stageTitles: Record<SupplyChainReviewStageId, string>;
  stageDetails: Record<SupplyChainReviewStageId, string>;
  primaryLabels: Record<SupplyChainReviewStageId, string>;
  secondaryLabels: Record<SupplyChainReviewStageId, string>;
  status: Record<"pass" | "warning" | "fail", string>;
}

const copy: Record<Locale, SupplyChainReadinessText> = {
  ja: { nav: "審査の現在地", title: "ライセンス・脆弱性審査", intro: "ロックファイルからリリース判定までの4段階を、現在の証跡だけで集約します。", ready: "リリース審査を通過", review: "確認が必要です", blocked: "リリースを停止中", blockers: "ブロッカー", warnings: "要確認", digest: "依存関係ダイジェスト", open: "確認する", privacy: "OSVへの送信は自動実行されません。送信項目を確認し、専用チェックボックスで同意した場合だけ照会します。", stageTitles: { inventory: "依存関係を確定", evidence: "ライセンス証跡を収集", licenseReview: "判断を記録", advisories: "脆弱性を照会" }, stageDetails: { inventory: "固定されたロックファイルと配布元・整合性を確認します。", evidence: "端末内のパッケージ情報とライセンスファイルを照合します。", licenseReview: "不明・相互利用ライセンスを期限付きで承認、制限、拒否します。", advisories: "明示同意後だけ、最小3項目をOSVへ送信します。" }, primaryLabels: { inventory: "パッケージ", evidence: "完全な証跡", licenseReview: "判断済み", advisories: "照会済み" }, secondaryLabels: { inventory: "整合性問題", evidence: "未解決", licenseReview: "未解決", advisories: "脆弱性／未照会" }, status: { pass: "完了", warning: "要確認", fail: "停止" } },
  en: { nav: "Review status", title: "License & Vulnerability Review", intro: "Combines the four stages from lockfiles to the release decision using current evidence only.", ready: "Release review passed", review: "Review required", blocked: "Release blocked", blockers: "Blockers", warnings: "Needs review", digest: "Dependency digest", open: "Review", privacy: "OSV is never contacted automatically. A query runs only after you inspect the transmitted fields and approve the dedicated consent checkbox.", stageTitles: { inventory: "Lock dependency inventory", evidence: "Collect license evidence", licenseReview: "Record decisions", advisories: "Check vulnerabilities" }, stageDetails: { inventory: "Verify pinned lockfiles, sources, and integrity.", evidence: "Match local package metadata and license files.", licenseReview: "Approve, restrict, or block unknown and reciprocal licenses with an expiry.", advisories: "Send only three minimal fields to OSV after explicit consent." }, primaryLabels: { inventory: "Packages", evidence: "Complete evidence", licenseReview: "Reviewed", advisories: "Queried" }, secondaryLabels: { inventory: "Integrity issues", evidence: "Unresolved", licenseReview: "Unresolved", advisories: "Vulnerabilities / pending" }, status: { pass: "Complete", warning: "Review", fail: "Blocked" } },
  "zh-CN": { nav: "审查状态", title: "许可证与漏洞审查", intro: "仅使用当前证据汇总从锁文件到发布判定的四个阶段。", ready: "发布审查已通过", review: "需要审查", blocked: "发布已阻止", blockers: "阻止项", warnings: "待确认", digest: "依赖摘要", open: "查看", privacy: "不会自动联系 OSV。仅在检查发送字段并勾选专用同意框后才会查询。", stageTitles: { inventory: "锁定依赖清单", evidence: "收集许可证证据", licenseReview: "记录判定", advisories: "检查漏洞" }, stageDetails: { inventory: "验证锁文件、来源与完整性。", evidence: "核对本机包元数据和许可证文件。", licenseReview: "对未知和互惠许可证进行限期批准、限制或阻止。", advisories: "明确同意后仅向 OSV 发送三个最小字段。" }, primaryLabels: { inventory: "软件包", evidence: "完整证据", licenseReview: "已审查", advisories: "已查询" }, secondaryLabels: { inventory: "完整性问题", evidence: "未解决", licenseReview: "未解决", advisories: "漏洞／未查询" }, status: { pass: "完成", warning: "审查", fail: "阻止" } },
  "zh-TW": { nav: "審查狀態", title: "授權與漏洞審查", intro: "僅使用目前證據彙整從鎖定檔到發佈判定的四個階段。", ready: "發佈審查已通過", review: "需要審查", blocked: "發佈已阻擋", blockers: "阻擋項", warnings: "待確認", digest: "相依摘要", open: "查看", privacy: "不會自動連線 OSV。只有檢查傳送欄位並勾選專用同意框後才會查詢。", stageTitles: { inventory: "鎖定相依清單", evidence: "收集授權證據", licenseReview: "記錄判定", advisories: "檢查漏洞" }, stageDetails: { inventory: "驗證鎖定檔、來源與完整性。", evidence: "核對本機套件中繼資料與授權檔案。", licenseReview: "對未知與互惠授權進行限期核准、限制或阻擋。", advisories: "明確同意後僅向 OSV 傳送三個最小欄位。" }, primaryLabels: { inventory: "套件", evidence: "完整證據", licenseReview: "已審查", advisories: "已查詢" }, secondaryLabels: { inventory: "完整性問題", evidence: "未解決", licenseReview: "未解決", advisories: "漏洞／未查詢" }, status: { pass: "完成", warning: "審查", fail: "阻擋" } },
  ko: { nav: "검토 상태", title: "라이선스 및 취약점 검토", intro: "현재 증거만으로 잠금 파일부터 릴리스 판단까지 네 단계를 통합합니다.", ready: "릴리스 검토 통과", review: "검토 필요", blocked: "릴리스 차단됨", blockers: "차단 항목", warnings: "확인 필요", digest: "의존성 다이제스트", open: "검토", privacy: "OSV에 자동으로 접속하지 않습니다. 전송 필드를 확인하고 전용 동의 상자를 선택한 경우에만 조회합니다.", stageTitles: { inventory: "의존성 목록 고정", evidence: "라이선스 증거 수집", licenseReview: "판단 기록", advisories: "취약점 확인" }, stageDetails: { inventory: "잠금 파일, 출처 및 무결성을 확인합니다.", evidence: "로컬 패키지 메타데이터와 라이선스 파일을 대조합니다.", licenseReview: "알 수 없거나 상호 라이선스를 기한과 함께 승인, 제한 또는 차단합니다.", advisories: "명시적 동의 후 최소 세 필드만 OSV로 보냅니다." }, primaryLabels: { inventory: "패키지", evidence: "완전한 증거", licenseReview: "검토됨", advisories: "조회됨" }, secondaryLabels: { inventory: "무결성 문제", evidence: "미해결", licenseReview: "미해결", advisories: "취약점 / 미조회" }, status: { pass: "완료", warning: "검토", fail: "차단" } },
  es: { nav: "Estado de revisión", title: "Revisión de licencias y vulnerabilidades", intro: "Combina las cuatro etapas, desde los archivos de bloqueo hasta la decisión de publicación, usando solo evidencia actual.", ready: "Revisión de publicación aprobada", review: "Revisión necesaria", blocked: "Publicación bloqueada", blockers: "Bloqueos", warnings: "Requiere revisión", digest: "Resumen de dependencias", open: "Revisar", privacy: "Nunca se contacta con OSV automáticamente. La consulta solo se ejecuta después de revisar los campos enviados y aprobar la casilla de consentimiento.", stageTitles: { inventory: "Fijar inventario", evidence: "Recopilar evidencia", licenseReview: "Registrar decisiones", advisories: "Comprobar vulnerabilidades" }, stageDetails: { inventory: "Verifica archivos de bloqueo, orígenes e integridad.", evidence: "Compara metadatos y archivos de licencia locales.", licenseReview: "Aprueba, restringe o bloquea licencias desconocidas y recíprocas con caducidad.", advisories: "Envía solo tres campos mínimos a OSV tras el consentimiento explícito." }, primaryLabels: { inventory: "Paquetes", evidence: "Evidencia completa", licenseReview: "Revisados", advisories: "Consultados" }, secondaryLabels: { inventory: "Problemas de integridad", evidence: "Sin resolver", licenseReview: "Sin resolver", advisories: "Vulnerabilidades / pendiente" }, status: { pass: "Completo", warning: "Revisar", fail: "Bloqueado" } },
  de: { nav: "Prüfstatus", title: "Lizenz- und Schwachstellenprüfung", intro: "Fasst die vier Stufen von Lockdateien bis zur Freigabeentscheidung ausschließlich anhand aktueller Nachweise zusammen.", ready: "Freigabeprüfung bestanden", review: "Prüfung erforderlich", blocked: "Freigabe blockiert", blockers: "Blocker", warnings: "Zu prüfen", digest: "Abhängigkeits-Digest", open: "Prüfen", privacy: "OSV wird nie automatisch kontaktiert. Eine Abfrage erfolgt erst nach Prüfung der übertragenen Felder und ausdrücklicher Zustimmung.", stageTitles: { inventory: "Inventar fixieren", evidence: "Lizenznachweise sammeln", licenseReview: "Entscheidungen erfassen", advisories: "Schwachstellen prüfen" }, stageDetails: { inventory: "Lockdateien, Quellen und Integrität prüfen.", evidence: "Lokale Paketmetadaten und Lizenzdateien abgleichen.", licenseReview: "Unbekannte und reziproke Lizenzen befristet genehmigen, einschränken oder blockieren.", advisories: "Nach ausdrücklicher Zustimmung nur drei minimale Felder an OSV senden." }, primaryLabels: { inventory: "Pakete", evidence: "Vollständige Nachweise", licenseReview: "Geprüft", advisories: "Abgefragt" }, secondaryLabels: { inventory: "Integritätsprobleme", evidence: "Offen", licenseReview: "Offen", advisories: "Schwachstellen / offen" }, status: { pass: "Fertig", warning: "Prüfen", fail: "Blockiert" } },
  fr: { nav: "État de revue", title: "Revue des licences et vulnérabilités", intro: "Regroupe les quatre étapes, des fichiers verrouillés à la décision de publication, avec les seules preuves actuelles.", ready: "Revue de publication validée", review: "Revue nécessaire", blocked: "Publication bloquée", blockers: "Blocages", warnings: "À vérifier", digest: "Empreinte des dépendances", open: "Vérifier", privacy: "OSV n’est jamais contacté automatiquement. La requête ne part qu’après examen des champs transmis et consentement explicite.", stageTitles: { inventory: "Verrouiller l’inventaire", evidence: "Collecter les preuves", licenseReview: "Consigner les décisions", advisories: "Vérifier les vulnérabilités" }, stageDetails: { inventory: "Vérifie les fichiers verrouillés, les sources et l’intégrité.", evidence: "Compare les métadonnées locales et les fichiers de licence.", licenseReview: "Approuve, restreint ou bloque avec échéance les licences inconnues et réciproques.", advisories: "Envoie seulement trois champs minimaux à OSV après consentement explicite." }, primaryLabels: { inventory: "Paquets", evidence: "Preuves complètes", licenseReview: "Examinés", advisories: "Interrogés" }, secondaryLabels: { inventory: "Problèmes d’intégrité", evidence: "Non résolus", licenseReview: "Non résolus", advisories: "Vulnérabilités / attente" }, status: { pass: "Terminé", warning: "Vérifier", fail: "Bloqué" } },
  "pt-BR": { nav: "Status da revisão", title: "Revisão de licenças e vulnerabilidades", intro: "Reúne as quatro etapas, dos arquivos de bloqueio à decisão de lançamento, usando somente evidências atuais.", ready: "Revisão de lançamento aprovada", review: "Revisão necessária", blocked: "Lançamento bloqueado", blockers: "Bloqueios", warnings: "Precisa de revisão", digest: "Resumo das dependências", open: "Revisar", privacy: "O OSV nunca é contatado automaticamente. A consulta só ocorre após revisar os campos enviados e aceitar a caixa de consentimento específica.", stageTitles: { inventory: "Fixar inventário", evidence: "Coletar evidências", licenseReview: "Registrar decisões", advisories: "Verificar vulnerabilidades" }, stageDetails: { inventory: "Verifica arquivos de bloqueio, origens e integridade.", evidence: "Compara metadados locais e arquivos de licença.", licenseReview: "Aprova, restringe ou bloqueia licenças desconhecidas e recíprocas com validade.", advisories: "Envia apenas três campos mínimos ao OSV após consentimento explícito." }, primaryLabels: { inventory: "Pacotes", evidence: "Evidências completas", licenseReview: "Revisados", advisories: "Consultados" }, secondaryLabels: { inventory: "Problemas de integridade", evidence: "Não resolvidos", licenseReview: "Não resolvidos", advisories: "Vulnerabilidades / pendente" }, status: { pass: "Concluído", warning: "Revisar", fail: "Bloqueado" } },
};

export const supplyChainReadinessText = (locale: Locale) => copy[locale];
